common_users = [
            'anonymous',
            'root',
            'admin',
            'ftp',
            'ftpuser',
            'www-data',
            'administrator',
            'test',
            'nobody',
            'oracle',
            'mysql',
            'user',
            'webmaster',
            'postmaster',
            'uploader',
            'abc123',
            '123456',
            'support',
            'post',
            '111111',
            'sa',
            'pr',
            'sales',
            'accounting',
            'qwerty',
            'password',
            'marketing',
            'manager',
            'mail',
            'hr',
            'john',
            'anonymous', 
            'root', 
            'ftp',
            'admin',
            'localadmin', 
            'admin', 
            'apc', 
            'admin', 
            'Root', 
            'Admin', 
            'User', 
            'Guest', 
            'ftp', 
            'admin', 
            'a', 
            'admin', 
            'adtec', 
            'admin', 
            'none', 
            'instrument', 
            'user', 
            'root',
            'default', 
            'admin', 
            'nmt', 
            'admin', 
            'supervisor', 
            'user1', 
            'avery', 
            'IEIeMerge', 
            'ADMIN', 
            'beijer', 
            'Admin', 
            'admin', 
            'admin', 
            'root', 
            'se', 
            'admin', 
            'device', 
            'apc', 
            'dm', 
            'dmftp', 
            'httpadmin', 
            'user', 
            'MELSEC', 
            'QNUDECPU', 
            'ftp_boot', 
            'uploader', 
            'ftpuser', 
            'USER', 
            'qbf77101', 
            'ntpupdate', 
            'sysdiag', 
            'wsupgrade', 
            'pcfactory', 
            'loader', 
            'test', 
            'webserver', 
            'fdrusers', 
            'nic2212', 
            'user', 
            'su', 
            'MayGion', 
            'admin', 
            'PlcmSpIp'
        ]

common_pass = list(set(common_users))

# for p in common_users:
#     for j in common_users:
#         if p == j:
#             print(f"Found common user: {p}")

print('[')
for p in common_pass:
    print(f"'{p}',")

print(']')